/**
 * Complete Octane Node Type Definitions
 * Auto-generated from octaneids.proto
 *
 * Total nodes: 755
 * Categories: 26
 */

export interface NodeTypeInfo {
  name: string;
  color: string;
}

export interface NodeTypeCategory {
  [nodeType: string]: NodeTypeInfo;
}

export interface NodeTypeHierarchy {
  [category: string]: NodeTypeCategory;
}

/**
 * Complete Octane node type hierarchy with all 755 node types
 */
export const OCTANE_NODE_TYPES: NodeTypeHierarchy = {
  Cameras: {
    NT_CAM_BAKING: { name: 'Cam Baking', color: '#8B4513' },
    NT_CAM_OSL: { name: 'Cam Osl', color: '#8B4513' },
    NT_CAM_OSL_BAKING: { name: 'Cam Osl Baking', color: '#8B4513' },
    NT_CAM_PANORAMIC: { name: 'Cam Panoramic', color: '#8B4513' },
    NT_CAM_SIMULATED_LENS: { name: 'Cam Simulated Lens', color: '#8B4513' },
    NT_CAM_THINLENS: { name: 'Cam Thinlens', color: '#8B4513' },
    NT_CAM_UNIVERSAL: { name: 'Cam Universal', color: '#8B4513' },
  },
  Displacement: {
    NT_DISPLACEMENT: { name: 'Displacement', color: '#FF6B35' },
    NT_VERTEX_DISPLACEMENT: { name: 'Vertex Displacement', color: '#FF6B35' },
    NT_VERTEX_DISPLACEMENT_MIXER: { name: 'Vertex Displacement Mixer', color: '#FF6B35' },
  },
  Emission: {
    NT_EMIS_BLACKBODY: { name: 'Emis Blackbody', color: '#FFD700' },
    NT_EMIS_TEXTURE: { name: 'Emis Texture', color: '#FFD700' },
  },
  Environments: {
    NT_ENV_DAYLIGHT: { name: 'Env Daylight', color: '#87CEEB' },
    NT_ENV_PLANETARY: { name: 'Env Planetary', color: '#87CEEB' },
    NT_ENV_TEXTURE: { name: 'Env Texture', color: '#87CEEB' },
  },
  Geometry: {
    NT_GEO_DECAL: { name: 'Decal', color: '#32CD32' },
    NT_GEO_EXPORTER: { name: 'Geometry Exporter', color: '#32CD32' },
    NT_GEO_GAUSSIAN_SPLAT: { name: 'Gaussian Splat', color: '#32CD32' },
    NT_GEO_GROUP: { name: 'Geometry Group', color: '#32CD32' },
    NT_GEO_JOINT: { name: 'Joint', color: '#32CD32' },
    NT_GEO_MESH: { name: 'Mesh', color: '#32CD32' },
    NT_GEO_MESH_VOLUME: { name: 'Mesh Volume', color: '#32CD32' },
    NT_GEO_MESH_VOLUME_SDF: { name: 'Mesh Volume SDF', color: '#32CD32' },
    NT_GEO_OBJECT: { name: 'Scene', color: '#32CD32' },
    NT_GEO_OSL: { name: 'OSL Geometry', color: '#32CD32' },
    NT_GEO_PLACEMENT: { name: 'Placement', color: '#32CD32' },
    NT_GEO_PLANE: { name: 'Plane', color: '#32CD32' },
    NT_GEO_SCATTER: { name: 'Scatter', color: '#32CD32' },
    NT_GEO_SDF_ARRAY_CIRCULAR: { name: 'Geo Sdf Array Circular', color: '#32CD32' },
    NT_GEO_SDF_ARRAY_LINEAR: { name: 'Geo Sdf Array Linear', color: '#32CD32' },
    NT_GEO_SDF_AVOID: { name: 'Geo Sdf Avoid', color: '#32CD32' },
    NT_GEO_SDF_BOX: { name: 'Geo Sdf Box', color: '#32CD32' },
    NT_GEO_SDF_CAPSULE: { name: 'Geo Sdf Capsule', color: '#32CD32' },
    NT_GEO_SDF_CLIP: { name: 'Geo Sdf Clip', color: '#32CD32' },
    NT_GEO_SDF_CONE: { name: 'Geo Sdf Cone', color: '#32CD32' },
    NT_GEO_SDF_CYLINDER: { name: 'Geo Sdf Cylinder', color: '#32CD32' },
    NT_GEO_SDF_DISPLACEMENT: { name: 'Geo Sdf Displacement', color: '#32CD32' },
    NT_GEO_SDF_DOMAIN: { name: 'Geo Sdf Domain', color: '#32CD32' },
    NT_GEO_SDF_INK: { name: 'Geo Sdf Ink', color: '#32CD32' },
    NT_GEO_SDF_INSET: { name: 'Geo Sdf Inset', color: '#32CD32' },
    NT_GEO_SDF_INTERSECT: { name: 'Geo Sdf Intersect', color: '#32CD32' },
    NT_GEO_SDF_MIRROR: { name: 'Geo Sdf Mirror', color: '#32CD32' },
    NT_GEO_SDF_OFFSET: { name: 'Geo Sdf Offset', color: '#32CD32' },
    NT_GEO_SDF_PRISM: { name: 'Geo Sdf Prism', color: '#32CD32' },
    NT_GEO_SDF_PULL: { name: 'Geo Sdf Pull', color: '#32CD32' },
    NT_GEO_SDF_PUSH: { name: 'Geo Sdf Push', color: '#32CD32' },
    NT_GEO_SDF_REPEL: { name: 'Geo Sdf Repel', color: '#32CD32' },
    NT_GEO_SDF_SPHERE: { name: 'Geo Sdf Sphere', color: '#32CD32' },
    NT_GEO_SDF_SUBTRACT: { name: 'Geo Sdf Subtract', color: '#32CD32' },
    NT_GEO_SDF_TORUS: { name: 'Geo Sdf Torus', color: '#32CD32' },
    NT_GEO_SDF_TUBE: { name: 'Geo Sdf Tube', color: '#32CD32' },
    NT_GEO_SDF_UNION: { name: 'Geo Sdf Union', color: '#32CD32' },
    NT_GEO_UNIT_VOLUME: { name: 'Unit Volume', color: '#32CD32' },
    NT_GEO_VOLUME: { name: 'Volume', color: '#32CD32' },
    NT_GEO_VOLUME_SDF: { name: 'Volume SDF', color: '#32CD32' },
    NT_SCATTER_SURFACE: { name: 'Scatter on Surface', color: '#32CD32' },
    NT_SCATTER_VOLUME: { name: 'Scatter in Volume', color: '#32CD32' },
  },
  Input: {
    NT_BOOL: { name: 'Bool', color: '#9370DB' },
    NT_BOOL_LOGIC_OPERATOR: { name: 'Bool Logic Operator', color: '#9370DB' },
    NT_DIRECTORY: { name: 'Directory', color: '#9370DB' },
    NT_ENUM: { name: 'Enum', color: '#9370DB' },
    NT_FILE: { name: 'File', color: '#9370DB' },
    NT_FLOAT: { name: 'Float', color: '#9370DB' },
    NT_FLOAT_COMPONENT_MERGER: { name: 'Float Component Merger', color: '#9370DB' },
    NT_FLOAT_COMPONENT_PICKER: { name: 'Float Component Picker', color: '#9370DB' },
    NT_FLOAT_IF: { name: 'Float If', color: '#9370DB' },
    NT_FLOAT_MATH_BINARY: { name: 'Float Math Binary', color: '#9370DB' },
    NT_FLOAT_MATH_UNARY: { name: 'Float Math Unary', color: '#9370DB' },
    NT_FLOAT_RANGE: { name: 'Float Range', color: '#9370DB' },
    NT_FLOAT_RELATIONAL_OPERATOR: { name: 'Float Relational Operator', color: '#9370DB' },
    NT_FLOAT_TIME: { name: 'Float Time', color: '#9370DB' },
    NT_FLOAT_TO_INT: { name: 'Float To Int', color: '#9370DB' },
    NT_INT: { name: 'Int', color: '#9370DB' },
    NT_INT_COMPONENT_MERGER: { name: 'Int Component Merger', color: '#9370DB' },
    NT_INT_COMPONENT_PICKER: { name: 'Int Component Picker', color: '#9370DB' },
    NT_INT_FRAME_INDEX: { name: 'Int Frame Index', color: '#9370DB' },
    NT_INT_IF: { name: 'Int If', color: '#9370DB' },
    NT_INT_RELATIONAL_OPERATOR: { name: 'Int Relational Operator', color: '#9370DB' },
    NT_INT_TO_FLOAT: { name: 'Int To Float', color: '#9370DB' },
    NT_STRING: { name: 'String', color: '#9370DB' },
  },
  Kernels: {
    NT_KERN_DIRECTLIGHTING: { name: 'Kern Directlighting', color: '#FF1493' },
    NT_KERN_INFO: { name: 'Kern Info', color: '#FF1493' },
    NT_KERN_MATPREVIEW: { name: 'Kern Matpreview', color: '#FF1493' },
    NT_KERN_PATHTRACING: { name: 'Kern Pathtracing', color: '#FF1493' },
    NT_KERN_PHOTONTRACING: { name: 'Kern Photontracing', color: '#FF1493' },
    NT_KERN_PMC: { name: 'Kern Pmc', color: '#FF1493' },
  },
  Lights: {
    NT_LIGHT_ANALYTIC: { name: 'Light Analytic', color: '#FFFF00' },
    NT_LIGHT_ANALYTIC_INTERNAL: { name: 'Light Analytic Internal', color: '#FFFF00' },
    NT_LIGHT_DIRECTIONAL: { name: 'Light Directional', color: '#FFFF00' },
    NT_LIGHT_QUAD: { name: 'Light Quad', color: '#FFFF00' },
    NT_LIGHT_SPHERE: { name: 'Light Sphere', color: '#FFFF00' },
    NT_LIGHT_VOLUME_SPOT: { name: 'Light Volume Spot', color: '#FFFF00' },
    NT_TOON_DIRECTIONAL_LIGHT: { name: 'Toon Directional Light', color: '#FFFF00' },
    NT_TOON_POINT_LIGHT: { name: 'Toon Point Light', color: '#FFFF00' },
  },
  'Material layers': {
    NT_MAT_COMPOSITE: { name: 'Mat Composite', color: '#6495ED' },
    NT_MAT_DIFFUSE_LAYER: { name: 'Mat Diffuse Layer', color: '#6495ED' },
    NT_MAT_LAYER: { name: 'Mat Layer', color: '#6495ED' },
    NT_MAT_LAYER_GROUP: { name: 'Mat Layer Group', color: '#6495ED' },
    NT_MAT_METALLIC_LAYER: { name: 'Mat Metallic Layer', color: '#6495ED' },
    NT_MAT_SHEEN_LAYER: { name: 'Mat Sheen Layer', color: '#6495ED' },
    NT_MAT_SPECULAR_LAYER: { name: 'Mat Specular Layer', color: '#6495ED' },
  },
  Materials: {
    NT_MAT_CLIPPING: { name: 'Mat Clipping', color: '#4169E1' },
    NT_MAT_DIFFUSE: { name: 'Mat Diffuse', color: '#4169E1' },
    NT_MAT_GLOSSY: { name: 'Mat Glossy', color: '#4169E1' },
    NT_MAT_HAIR: { name: 'Mat Hair', color: '#4169E1' },
    NT_MAT_MAP: { name: 'Mat Map', color: '#4169E1' },
    NT_MAT_METAL: { name: 'Mat Metal', color: '#4169E1' },
    NT_MAT_MIX: { name: 'Mat Mix', color: '#4169E1' },
    NT_MAT_NULL: { name: 'Mat Null', color: '#4169E1' },
    NT_MAT_OPEN_PBR_SURFACE: { name: 'Mat Open Pbr Surface', color: '#4169E1' },
    NT_MAT_OSL: { name: 'Mat Osl', color: '#4169E1' },
    NT_MAT_PORTAL: { name: 'Mat Portal', color: '#4169E1' },
    NT_MAT_SHADOW_CATCHER: { name: 'Mat Shadow Catcher', color: '#4169E1' },
    NT_MAT_SPECULAR: { name: 'Mat Specular', color: '#4169E1' },
    NT_MAT_STANDARD_SURFACE: { name: 'Mat Standard Surface', color: '#4169E1' },
    NT_MAT_TOON: { name: 'Mat Toon', color: '#4169E1' },
    NT_MAT_UNIVERSAL: { name: 'Mat Universal', color: '#4169E1' },
  },
  Medium: {
    NT_MED_ABSORPTION: { name: 'Med Absorption', color: '#8A2BE2' },
    NT_MED_RANDOMWALK: { name: 'Med Randomwalk', color: '#8A2BE2' },
    NT_MED_SCATTERING: { name: 'Med Scattering', color: '#8A2BE2' },
    NT_MED_STANDARD_VOLUME: { name: 'Med Standard Volume', color: '#8A2BE2' },
    NT_MED_VOLUME: { name: 'Med Volume', color: '#8A2BE2' },
    NT_PHASE_SCHLICK: { name: 'Phase Schlick', color: '#8A2BE2' },
  },
  Other: {
    NT_ANNOTATION: { name: 'Annotation', color: '#A9A9A9' },
    NT_IMPORT_ALEMBIC_PREFS: { name: 'Import Alembic Prefs', color: '#A9A9A9' },
    NT_IMPORT_FBX_PREFS: { name: 'Import Fbx Prefs', color: '#A9A9A9' },
    NT_IMPORT_IMAGE_PREFS: { name: 'Import Image Prefs', color: '#A9A9A9' },
    NT_IMPORT_MATERIALX_PREFS: { name: 'Import Materialx Prefs', color: '#A9A9A9' },
    NT_IMPORT_OBJ_PREFS: { name: 'Import Obj Prefs', color: '#A9A9A9' },
    NT_IMPORT_USD_PREFS: { name: 'Import Usd Prefs', color: '#A9A9A9' },
    NT_IMPORT_VDB_PREFS: { name: 'Import Vdb Prefs', color: '#A9A9A9' },
    NT_LOCAL_APP_PREFS: { name: 'Local App Prefs', color: '#A9A9A9' },
    NT_MATERIALX_RANGE_END: { name: 'Materialx Range End', color: '#A9A9A9' },
    NT_MATERIALX_RANGE_START: { name: 'Materialx Range Start', color: '#A9A9A9' },
    NT_METADATA: { name: 'Metadata', color: '#A9A9A9' },
    NT_OUT_ANIMATION_SETTINGS: { name: 'Out Animation Settings', color: '#A9A9A9' },
    NT_OUT_BIT_MASK: { name: 'Out Bit Mask', color: '#A9A9A9' },
    NT_OUT_BLENDING_SETTINGS: { name: 'Out Blending Settings', color: '#A9A9A9' },
    NT_OUT_BOOL: { name: 'Out Bool', color: '#A9A9A9' },
    NT_OUT_CAMERA: { name: 'Out Camera', color: '#A9A9A9' },
    NT_OUT_DISPLACEMENT: { name: 'Out Displacement', color: '#A9A9A9' },
    NT_OUT_EMISSION: { name: 'Out Emission', color: '#A9A9A9' },
    NT_OUT_ENUM: { name: 'Out Enum', color: '#A9A9A9' },
    NT_OUT_ENVIRONMENT: { name: 'Out Environment', color: '#A9A9A9' },
    NT_OUT_FILM_SETTINGS: { name: 'Out Film Settings', color: '#A9A9A9' },
    NT_OUT_FLOAT: { name: 'Out Float', color: '#A9A9A9' },
    NT_OUT_GEOMETRY: { name: 'Out Geometry', color: '#A9A9A9' },
    NT_OUT_IMAGER: { name: 'Out Imager', color: '#A9A9A9' },
    NT_OUT_INT: { name: 'Out Int', color: '#A9A9A9' },
    NT_OUT_KERNEL: { name: 'Out Kernel', color: '#A9A9A9' },
    NT_OUT_LUT: { name: 'Out Lut', color: '#A9A9A9' },
    NT_OUT_MATERIAL: { name: 'Out Material', color: '#A9A9A9' },
    NT_OUT_MATERIAL_LAYER: { name: 'Out Material Layer', color: '#A9A9A9' },
    NT_OUT_MEDIUM: { name: 'Out Medium', color: '#A9A9A9' },
    NT_OUT_OBJECTLAYER: { name: 'Out Objectlayer', color: '#A9A9A9' },
    NT_OUT_OCIO_COLOR_SPACE: { name: 'Out Ocio Color Space', color: '#A9A9A9' },
    NT_OUT_OCIO_LOOK: { name: 'Out Ocio Look', color: '#A9A9A9' },
    NT_OUT_OCIO_VIEW: { name: 'Out Ocio View', color: '#A9A9A9' },
    NT_OUT_OFFSET: { name: 'Out Offset', color: '#A9A9A9' },
    NT_OUT_OUTPUT_AOV: { name: 'Out Output Aov', color: '#A9A9A9' },
    NT_OUT_OUTPUT_AOV_GROUP: { name: 'Out Output Aov Group', color: '#A9A9A9' },
    NT_OUT_OUTPUT_AOV_LAYER: { name: 'Out Output Aov Layer', color: '#A9A9A9' },
    NT_OUT_PHASEFUNCTION: { name: 'Out Phasefunction', color: '#A9A9A9' },
    NT_OUT_POSTPROCESSING: { name: 'Out Postprocessing', color: '#A9A9A9' },
    NT_OUT_POST_VOLUME: { name: 'Out Post Volume', color: '#A9A9A9' },
    NT_OUT_PROJECTION: { name: 'Out Projection', color: '#A9A9A9' },
    NT_OUT_RENDERTARGET: { name: 'Out Rendertarget', color: '#A9A9A9' },
    NT_OUT_RENDER_JOB: { name: 'Out Render Job', color: '#A9A9A9' },
    NT_OUT_RENDER_LAYER: { name: 'Out Render Layer', color: '#A9A9A9' },
    NT_OUT_RENDER_PASSES: { name: 'Out Render Passes', color: '#A9A9A9' },
    NT_OUT_ROUND_EDGES: { name: 'Out Round Edges', color: '#A9A9A9' },
    NT_OUT_STRING: { name: 'Out String', color: '#A9A9A9' },
    NT_OUT_TEXTURE: { name: 'Out Texture', color: '#A9A9A9' },
    NT_OUT_TEX_COMPOSITE_LAYER: { name: 'Out Tex Composite Layer', color: '#A9A9A9' },
    NT_OUT_TOON_RAMP: { name: 'Out Toon Ramp', color: '#A9A9A9' },
    NT_OUT_TRACE_SET_VISIBILITY_RULE: { name: 'Out Trace Set Visibility Rule', color: '#A9A9A9' },
    NT_OUT_TRACE_SET_VISIBILITY_RULE_GROUP: {
      name: 'Out Trace Set Visibility Rule Group',
      color: '#A9A9A9',
    },
    NT_OUT_TRANSFORM: { name: 'Out Transform', color: '#A9A9A9' },
    NT_OUT_VOLUME_RAMP: { name: 'Out Volume Ramp', color: '#A9A9A9' },
    NT_PROGRAMMABLE_GRAPH_INPUT: { name: 'Programmable Graph Input', color: '#A9A9A9' },
    NT_PROJECT_SETTINGS: { name: 'Project Settings', color: '#A9A9A9' },
    NT_RENDER_AOV_GROUP: { name: 'Render Aov Group', color: '#A9A9A9' },
    NT_RNDR_VERSION: { name: 'Rndr Version', color: '#A9A9A9' },
    NT_SPLIT_PANE: { name: 'Split Pane', color: '#A9A9A9' },
    NT_UNKNOWN: { name: 'Unknown', color: '#A9A9A9' },
    NT_VEC_ROTATION: { name: 'Vec Rotation', color: '#A9A9A9' },
    NT_WORK_PANE: { name: 'Work Pane', color: '#A9A9A9' },
  },
  Output: {
    NT_IMAGER_CAMERA: { name: 'Imager Camera', color: '#DDA0DD' },
    NT_POSTPROCESSING: { name: 'Postprocessing', color: '#DDA0DD' },
    NT_POST_VOLUME: { name: 'Post Volume', color: '#DDA0DD' },
  },
  'Output AOVs': {
    NT_BLENDING_SETTINGS: { name: 'Blending Settings', color: '#FF1493' },
    NT_COMPOSITE_AOV_LAYER: { name: 'Composite Aov Layer', color: '#FF1493' },
    NT_OUTPUT_AOV: { name: 'Output Aov', color: '#FF1493' },
    NT_OUTPUT_AOV_CLAMP: { name: 'Output Aov Clamp', color: '#FF1493' },
    NT_OUTPUT_AOV_COLOR: { name: 'Output Aov Color', color: '#FF1493' },
    NT_OUTPUT_AOV_COLOR_CORRECTION: { name: 'Output Aov Color Correction', color: '#FF1493' },
    NT_OUTPUT_AOV_COMPOSITE: { name: 'Output Aov Composite', color: '#FF1493' },
    NT_OUTPUT_AOV_CRYPTOMATTE_MASK: { name: 'Output Aov Cryptomatte Mask', color: '#FF1493' },
    NT_OUTPUT_AOV_GROUP: { name: 'Output Aov Group', color: '#FF1493' },
    NT_OUTPUT_AOV_IMAGE: { name: 'Output Aov Image', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_ADD_BLOOM: { name: 'Output Aov Layer Add Bloom', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_ADD_CHROMATIC_ABERRATION: {
      name: 'Output Aov Layer Add Chromatic Aberration',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_ADD_GLARE: { name: 'Output Aov Layer Add Glare', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_ADD_LENS_FLARE: {
      name: 'Output Aov Layer Add Lens Flare',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_ADD_VIGNETTE: { name: 'Output Aov Layer Add Vignette', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_ADJUST_BRIGHTNESS: {
      name: 'Output Aov Layer Adjust Brightness',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_ADJUST_CONTRAST: {
      name: 'Output Aov Layer Adjust Contrast',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_ADJUST_HUE: { name: 'Output Aov Layer Adjust Hue', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_ADJUST_OPACITY: {
      name: 'Output Aov Layer Adjust Opacity',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_ADJUST_SATURATION: {
      name: 'Output Aov Layer Adjust Saturation',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_ADJUST_WHITE_BALANCE: {
      name: 'Output Aov Layer Adjust White Balance',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_APPLY_CAMERA_RESPONSE_CURVE: {
      name: 'Output Aov Layer Apply Camera Response Curve',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_APPLY_CUSTOM_CURVE: {
      name: 'Output Aov Layer Apply Custom Curve',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_APPLY_GAMMA_CURVE: {
      name: 'Output Aov Layer Apply Gamma Curve',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_APPLY_IMAGER_AND_POST_PROCESSING: {
      name: 'Output Aov Layer Apply Imager And Post Processing',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_APPLY_LUT: { name: 'Output Aov Layer Apply Lut', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_APPLY_OCIO_LOOK: {
      name: 'Output Aov Layer Apply Ocio Look',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_BLEND_CRYPTOMATTE_MASK: {
      name: 'Output Aov Layer Blend Cryptomatte Mask',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_BLEND_IMAGE: { name: 'Output Aov Layer Blend Image', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_BLEND_LAYERS: { name: 'Output Aov Layer Blend Layers', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_BLEND_LIGHT_MIXER: {
      name: 'Output Aov Layer Blend Light Mixer',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_BLEND_RENDER_AOV: {
      name: 'Output Aov Layer Blend Render Aov',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_BLEND_SHARED_SURFACE: {
      name: 'Output Aov Layer Blend Shared Surface',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_BLEND_SOLID_COLOR: {
      name: 'Output Aov Layer Blend Solid Color',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_BLEND_TEXTURE: { name: 'Output Aov Layer Blend Texture', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_BLUR: { name: 'Output Aov Layer Blur', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_BOOST_HIGHLIGHTS: {
      name: 'Output Aov Layer Boost Highlights',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_CLAMP: { name: 'Output Aov Layer Clamp', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_CONVERT_FOR_SDR_DISPLAY_ACES: {
      name: 'Output Aov Layer Convert For Sdr Display Aces',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_CONVERT_FOR_SDR_DISPLAY_AGX: {
      name: 'Output Aov Layer Convert For Sdr Display Agx',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_CONVERT_FOR_SDR_DISPLAY_BASIC: {
      name: 'Output Aov Layer Convert For Sdr Display Basic',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_CONVERT_FOR_SDR_DISPLAY_OCIO: {
      name: 'Output Aov Layer Convert For Sdr Display Ocio',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_CONVERT_FOR_SDR_DISPLAY_SMOOTH: {
      name: 'Output Aov Layer Convert For Sdr Display Smooth',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_DISCARD_CHECKPOINT: {
      name: 'Output Aov Layer Discard Checkpoint',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_DITHER: { name: 'Output Aov Layer Dither', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_EXPAND_CONTRACT: {
      name: 'Output Aov Layer Expand Contract',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_GROUP: { name: 'Output Aov Layer Group', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_INVERT: { name: 'Output Aov Layer Invert', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_LOAD_CHECKPOINT: {
      name: 'Output Aov Layer Load Checkpoint',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_MAP_RANGE: { name: 'Output Aov Layer Map Range', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_MASK_WITH_CRYPTOMATTE: {
      name: 'Output Aov Layer Mask With Cryptomatte',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_MASK_WITH_LAYERS: {
      name: 'Output Aov Layer Mask With Layers',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_OPEN_IMAGE_DENOISE: {
      name: 'Output Aov Layer Open Image Denoise',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_REMOVE_HOT_PIXELS: {
      name: 'Output Aov Layer Remove Hot Pixels',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_REBLEND: { name: 'Output Aov Layer Reblend', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_SAVE_CHECKPOINT: {
      name: 'Output Aov Layer Save Checkpoint',
      color: '#FF1493',
    },
    NT_OUTPUT_AOV_LAYER_SHARPEN: { name: 'Output Aov Layer Sharpen', color: '#FF1493' },
    NT_OUTPUT_AOV_LAYER_UNBLEND: { name: 'Output Aov Layer Unblend', color: '#FF1493' },
    NT_OUTPUT_AOV_LIGHT_MIXING: { name: 'Output Aov Light Mixing', color: '#FF1493' },
    NT_OUTPUT_AOV_MAP_RANGE: { name: 'Output Aov Map Range', color: '#FF1493' },
    NT_OUTPUT_AOV_RENDER: { name: 'Output Aov Render', color: '#FF1493' },
    NT_OUTPUT_AOV_SHARED_SURFACE: { name: 'Output Aov Shared Surface', color: '#FF1493' },
  },
  Projection: {
    NT_PROJ_BOX: { name: 'Proj Box', color: '#FF8C00' },
    NT_PROJ_COLOR_TO_UVW: { name: 'Proj Color To Uvw', color: '#FF8C00' },
    NT_PROJ_CYLINDRICAL: { name: 'Proj Cylindrical', color: '#FF8C00' },
    NT_PROJ_DISTORTED_MESH_UV: { name: 'Proj Distorted Mesh Uv', color: '#FF8C00' },
    NT_PROJ_DISTORTED_UVW: { name: 'Proj Distorted Uvw', color: '#FF8C00' },
    NT_PROJ_INSTANCE_POSITION: { name: 'Proj Instance Position', color: '#FF8C00' },
    NT_PROJ_LINEAR: { name: 'Proj Linear', color: '#FF8C00' },
    NT_PROJ_MATCAP: { name: 'Proj Matcap', color: '#FF8C00' },
    NT_PROJ_OSL: { name: 'Proj Osl', color: '#FF8C00' },
    NT_PROJ_OSL_UV: { name: 'Proj Osl Uv', color: '#FF8C00' },
    NT_PROJ_PERSPECTIVE: { name: 'Proj Perspective', color: '#FF8C00' },
    NT_PROJ_SAMPLE_POSITION: { name: 'Proj Sample Position', color: '#FF8C00' },
    NT_PROJ_SPHERICAL: { name: 'Proj Spherical', color: '#FF8C00' },
    NT_PROJ_TRIPLANAR: { name: 'Proj Triplanar', color: '#FF8C00' },
    NT_PROJ_UVW: { name: 'Proj Uvw', color: '#FF8C00' },
  },
  'Render AOVs': {
    NT_AOV_ALPHA: { name: 'Aov Alpha', color: '#FF69B4' },
    NT_AOV_AMBIENT_OCCLUSION: { name: 'Aov Ambient Occlusion', color: '#FF69B4' },
    NT_AOV_BAKING_GROUP_ID: { name: 'Aov Baking Group Id', color: '#FF69B4' },
    NT_AOV_CAMERA_MASK: { name: 'Aov Camera Mask', color: '#FF69B4' },
    NT_AOV_CRYPTOMATTE: { name: 'Aov Cryptomatte', color: '#FF69B4' },
    NT_AOV_CUSTOM: { name: 'Aov Custom', color: '#FF69B4' },
    NT_AOV_DENOISE_ALBEDO: { name: 'Aov Denoise Albedo', color: '#FF69B4' },
    NT_AOV_DENOISE_HIT_DISTANCE: { name: 'Aov Denoise Hit Distance', color: '#FF69B4' },
    NT_AOV_DENOISE_NORMAL: { name: 'Aov Denoise Normal', color: '#FF69B4' },
    NT_AOV_DENOISE_ROUGHNESS: { name: 'Aov Denoise Roughness', color: '#FF69B4' },
    NT_AOV_DIFFUSE: { name: 'Aov Diffuse', color: '#FF69B4' },
    NT_AOV_DIFFUSE_DIRECT: { name: 'Aov Diffuse Direct', color: '#FF69B4' },
    NT_AOV_DIFFUSE_DIRECT_DENOISER_OUTPUT: {
      name: 'Aov Diffuse Direct Denoiser Output',
      color: '#FF69B4',
    },
    NT_AOV_DIFFUSE_FILTER: { name: 'Aov Diffuse Filter', color: '#FF69B4' },
    NT_AOV_DIFFUSE_FILTER_INFO: { name: 'Aov Diffuse Filter Info', color: '#FF69B4' },
    NT_AOV_DIFFUSE_INDIRECT: { name: 'Aov Diffuse Indirect', color: '#FF69B4' },
    NT_AOV_DIFFUSE_INDIRECT_DENOISER_OUTPUT: {
      name: 'Aov Diffuse Indirect Denoiser Output',
      color: '#FF69B4',
    },
    NT_AOV_EMISSION_DENOISER_OUTPUT: { name: 'Aov Emission Denoiser Output', color: '#FF69B4' },
    NT_AOV_EMIT: { name: 'Aov Emit', color: '#FF69B4' },
    NT_AOV_ENVIRONMENT: { name: 'Aov Environment', color: '#FF69B4' },
    NT_AOV_ENVIRONMENT_UNOCCLUDED: { name: 'Aov Environment Unoccluded', color: '#FF69B4' },
    NT_AOV_GAUSSIAN_SPLAT: { name: 'Aov Gaussian Splat', color: '#FF69B4' },
    NT_AOV_GAUSSIAN_SPLAT_INFO: { name: 'Aov Gaussian Splat Info', color: '#FF69B4' },
    NT_AOV_GEOMETRIC_NORMAL: { name: 'Aov Geometric Normal', color: '#FF69B4' },
    NT_AOV_GLOBAL_TEX: { name: 'Aov Global Tex', color: '#FF69B4' },
    NT_AOV_IOR: { name: 'Aov Ior', color: '#FF69B4' },
    NT_AOV_IRRADIANCE: { name: 'Aov Irradiance', color: '#FF69B4' },
    NT_AOV_LAYER_BLACK_SHADOWS: { name: 'Aov Layer Black Shadows', color: '#FF69B4' },
    NT_AOV_LAYER_REFLECTIONS: { name: 'Aov Layer Reflections', color: '#FF69B4' },
    NT_AOV_LAYER_SHADOWS: { name: 'Aov Layer Shadows', color: '#FF69B4' },
    NT_AOV_LIGHT: { name: 'Aov Light', color: '#FF69B4' },
    NT_AOV_LIGHT_DIRECT: { name: 'Aov Light Direct', color: '#FF69B4' },
    NT_AOV_LIGHT_DIRECTION: { name: 'Aov Light Direction', color: '#FF69B4' },
    NT_AOV_LIGHT_INDIRECT: { name: 'Aov Light Indirect', color: '#FF69B4' },
    NT_AOV_LIGHT_PASS_ID: { name: 'Aov Light Pass Id', color: '#FF69B4' },
    NT_AOV_MATERIAL_ID: { name: 'Aov Material Id', color: '#FF69B4' },
    NT_AOV_MOTION_VECTOR: { name: 'Aov Motion Vector', color: '#FF69B4' },
    NT_AOV_NOISE_BEAUTY: { name: 'Aov Noise Beauty', color: '#FF69B4' },
    NT_AOV_NOISE_DIFFUSE_DIRECT: { name: 'Aov Noise Diffuse Direct', color: '#FF69B4' },
    NT_AOV_NOISE_DIFFUSE_INDIRECT: { name: 'Aov Noise Diffuse Indirect', color: '#FF69B4' },
    NT_AOV_NOISE_REFLECTION_DIRECT: { name: 'Aov Noise Reflection Direct', color: '#FF69B4' },
    NT_AOV_NOISE_REFLECTION_INDIRECT: { name: 'Aov Noise Reflection Indirect', color: '#FF69B4' },
    NT_AOV_OBJECT_ID: { name: 'Aov Object Id', color: '#FF69B4' },
    NT_AOV_OBJECT_LAYER_COLOR: { name: 'Aov Object Layer Color', color: '#FF69B4' },
    NT_AOV_OPACITY: { name: 'Aov Opacity', color: '#FF69B4' },
    NT_AOV_POSITION: { name: 'Aov Position', color: '#FF69B4' },
    NT_AOV_POSTFX_MEDIA: { name: 'Aov Postfx Media', color: '#FF69B4' },
    NT_AOV_POST_PROCESSING: { name: 'Aov Post Processing', color: '#FF69B4' },
    NT_AOV_PRIMARY_HIT_DATA: { name: 'Aov Primary Hit Data', color: '#FF69B4' },
    NT_AOV_PRIMARY_ZDEPTH: { name: 'Aov Primary Zdepth', color: '#FF69B4' },
    NT_AOV_PRIMITIVE_TYPE: { name: 'Aov Primitive Type', color: '#FF69B4' },
    NT_AOV_REFLECTION: { name: 'Aov Reflection', color: '#FF69B4' },
    NT_AOV_REFLECTION_DIRECT: { name: 'Aov Reflection Direct', color: '#FF69B4' },
    NT_AOV_REFLECTION_DIRECT_DENOISER_OUTPUT: {
      name: 'Aov Reflection Direct Denoiser Output',
      color: '#FF69B4',
    },
    NT_AOV_REFLECTION_FILTER: { name: 'Aov Reflection Filter', color: '#FF69B4' },
    NT_AOV_REFLECTION_FILTER_INFO: { name: 'Aov Reflection Filter Info', color: '#FF69B4' },
    NT_AOV_REFLECTION_INDIRECT: { name: 'Aov Reflection Indirect', color: '#FF69B4' },
    NT_AOV_REFLECTION_INDIRECT_DENOISER_OUTPUT: {
      name: 'Aov Reflection Indirect Denoiser Output',
      color: '#FF69B4',
    },
    NT_AOV_REFRACTION: { name: 'Aov Refraction', color: '#FF69B4' },
    NT_AOV_REFRACTION_FILTER: { name: 'Aov Refraction Filter', color: '#FF69B4' },
    NT_AOV_REFRACTION_FILTER_INFO: { name: 'Aov Refraction Filter Info', color: '#FF69B4' },
    NT_AOV_REMAINDER_DENOISER_OUTPUT: { name: 'Aov Remainder Denoiser Output', color: '#FF69B4' },
    NT_AOV_RENDER_LAYER_ID: { name: 'Aov Render Layer Id', color: '#FF69B4' },
    NT_AOV_RENDER_LAYER_MASK: { name: 'Aov Render Layer Mask', color: '#FF69B4' },
    NT_AOV_ROUGHNESS: { name: 'Aov Roughness', color: '#FF69B4' },
    NT_AOV_SAMPLE_OFFSET: { name: 'Aov Sample Offset', color: '#FF69B4' },
    NT_AOV_SECONDARY_RAY_LENGTHS: { name: 'Aov Secondary Ray Lengths', color: '#FF69B4' },
    NT_AOV_SHADING_NORMAL: { name: 'Aov Shading Normal', color: '#FF69B4' },
    NT_AOV_SHADOW: { name: 'Aov Shadow', color: '#FF69B4' },
    NT_AOV_SMOOTH_NORMAL: { name: 'Aov Smooth Normal', color: '#FF69B4' },
    NT_AOV_SSS: { name: 'Aov Sss', color: '#FF69B4' },
    NT_AOV_TANGENT_NORMAL: { name: 'Aov Tangent Normal', color: '#FF69B4' },
    NT_AOV_TANGENT_U: { name: 'Aov Tangent U', color: '#FF69B4' },
    NT_AOV_TIME: { name: 'Aov Time', color: '#FF69B4' },
    NT_AOV_TRACE_CLOCK: { name: 'Aov Trace Clock', color: '#FF69B4' },
    NT_AOV_TRANSMISSION: { name: 'Aov Transmission', color: '#FF69B4' },
    NT_AOV_TRANSMISSION_FILTER: { name: 'Aov Transmission Filter', color: '#FF69B4' },
    NT_AOV_TRANSMISSION_FILTER_INFO: { name: 'Aov Transmission Filter Info', color: '#FF69B4' },
    NT_AOV_UV_COORD: { name: 'Aov Uv Coord', color: '#FF69B4' },
    NT_AOV_VOLUME: { name: 'Aov Volume', color: '#FF69B4' },
    NT_AOV_VOLUME_DENOISER_OUTPUT: { name: 'Aov Volume Denoiser Output', color: '#FF69B4' },
    NT_AOV_VOLUME_EMISSION: { name: 'Aov Volume Emission', color: '#FF69B4' },
    NT_AOV_VOLUME_EMISSION_DENOISER_OUTPUT: {
      name: 'Aov Volume Emission Denoiser Output',
      color: '#FF69B4',
    },
    NT_AOV_VOLUME_MASK: { name: 'Aov Volume Mask', color: '#FF69B4' },
    NT_AOV_VOLUME_Z_DEPTH_BACK: { name: 'Aov Volume Z Depth Back', color: '#FF69B4' },
    NT_AOV_VOLUME_Z_DEPTH_FRONT: { name: 'Aov Volume Z Depth Front', color: '#FF69B4' },
    NT_AOV_WIREFRAME: { name: 'Aov Wireframe', color: '#FF69B4' },
    NT_AOV_Z_DEPTH: { name: 'Aov Z Depth', color: '#FF69B4' },
  },
  'Render job': {
    NT_RENDER_JOB_GROUP: { name: 'Render Job Group', color: '#CD853F' },
  },
  'Render settings': {
    NT_ANIMATION_SETTINGS: { name: 'Animation Settings', color: '#FFA500' },
    NT_FILM_SETTINGS: { name: 'Film Settings', color: '#FFA500' },
    NT_IMAGE_RESOLUTION: { name: 'Image Resolution', color: '#FFA500' },
    NT_RENDER_LAYER: { name: 'Render Layer', color: '#FFA500' },
    NT_RENDER_PASSES: { name: 'Render Passes', color: '#FFA500' },
  },
  'Round edges': {
    NT_ROUND_EDGES: { name: 'Round Edges', color: '#FFB6C1' },
  },
  'Texture layers': {
    NT_TEX_COMPOSITE: { name: 'Tex Composite', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER: { name: 'Tex Composite Layer', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_ADJUST_BRIGHTNESS: {
      name: 'Tex Composite Layer Adjust Brightness',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_ADJUST_COLOR_BALANCE: {
      name: 'Tex Composite Layer Adjust Color Balance',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_ADJUST_CONTRAST: {
      name: 'Tex Composite Layer Adjust Contrast',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_ADJUST_EXPOSURE: {
      name: 'Tex Composite Layer Adjust Exposure',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_ADJUST_HUE: { name: 'Tex Composite Layer Adjust Hue', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_ADJUST_LIGHTNESS: {
      name: 'Tex Composite Layer Adjust Lightness',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_ADJUST_SATURATION: {
      name: 'Tex Composite Layer Adjust Saturation',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_ADJUST_SATURATION_HSL: {
      name: 'Tex Composite Layer Adjust Saturation Hsl',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_ADJUST_WHITE_BALANCE: {
      name: 'Tex Composite Layer Adjust White Balance',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_APPLY_CUSTOM_CURVE: {
      name: 'Tex Composite Layer Apply Custom Curve',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_APPLY_GAMMA_CURVE: {
      name: 'Tex Composite Layer Apply Gamma Curve',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_APPLY_GRADIENT_MAP: {
      name: 'Tex Composite Layer Apply Gradient Map',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_APPLY_LUT: { name: 'Tex Composite Layer Apply Lut', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_CHANNEL_MIXER: {
      name: 'Tex Composite Layer Channel Mixer',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_CLAMP: { name: 'Tex Composite Layer Clamp', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_COMPARISON: { name: 'Tex Composite Layer Comparison', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_GRAYSCALE: { name: 'Tex Composite Layer Grayscale', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_GROUP: { name: 'Tex Composite Layer Group', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_MAP_RANGE: { name: 'Tex Composite Layer Map Range', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_MASK_WITH_LAYERS: {
      name: 'Tex Composite Layer Mask With Layers',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_MATH_BINARY: {
      name: 'Tex Composite Layer Math Binary',
      color: '#48D1CC',
    },
    NT_TEX_COMPOSITE_LAYER_MATH_UNARY: { name: 'Tex Composite Layer Math Unary', color: '#48D1CC' },
    NT_TEX_COMPOSITE_LAYER_THRESHOLD: { name: 'Tex Composite Layer Threshold', color: '#48D1CC' },
  },
  Textures: {
    NT_TEX_ADD: { name: 'Tex Add', color: '#20B2AA' },
    NT_TEX_ALPHAIMAGE: { name: 'Tex Alphaimage', color: '#20B2AA' },
    NT_TEX_BAKED_IMAGE: { name: 'Tex Baked Image', color: '#20B2AA' },
    NT_TEX_C4D_NOISE: { name: 'Tex C4d Noise', color: '#20B2AA' },
    NT_TEX_CAPTURE: { name: 'Tex Capture', color: '#20B2AA' },
    NT_TEX_CELLNOISE: { name: 'Tex Cellnoise', color: '#20B2AA' },
    NT_TEX_CHAINMAIL: { name: 'Tex Chainmail', color: '#20B2AA' },
    NT_TEX_CHANNEL_INVERT: { name: 'Tex Channel Invert', color: '#20B2AA' },
    NT_TEX_CHANNEL_MAP: { name: 'Tex Channel Map', color: '#20B2AA' },
    NT_TEX_CHANNEL_MERGE: { name: 'Tex Channel Merge', color: '#20B2AA' },
    NT_TEX_CHANNEL_PICK: { name: 'Tex Channel Pick', color: '#20B2AA' },
    NT_TEX_CHAOS: { name: 'Tex Chaos', color: '#20B2AA' },
    NT_TEX_CHECKS: { name: 'Tex Checks', color: '#20B2AA' },
    NT_TEX_CIRCLE_SPIRAL: { name: 'Tex Circle Spiral', color: '#20B2AA' },
    NT_TEX_CLAMP: { name: 'Tex Clamp', color: '#20B2AA' },
    NT_TEX_COLORCORRECTION: { name: 'Tex Colorcorrection', color: '#20B2AA' },
    NT_TEX_COLOR_KEY: { name: 'Tex Color Key', color: '#20B2AA' },
    NT_TEX_COLOR_SPACE_CONVERSION: { name: 'Tex Color Space Conversion', color: '#20B2AA' },
    NT_TEX_COLOR_SQUARES: { name: 'Tex Color Squares', color: '#20B2AA' },
    NT_TEX_COLOUR_VERTEXATTRIBUTE: { name: 'Tex Colour Vertexattribute', color: '#20B2AA' },
    NT_TEX_COMPARE: { name: 'Tex Compare', color: '#20B2AA' },
    NT_TEX_COSINEMIX: { name: 'Tex Cosinemix', color: '#20B2AA' },
    NT_TEX_CURVATURE: { name: 'Tex Curvature', color: '#20B2AA' },
    NT_TEX_DECAL: { name: 'Tex Decal', color: '#20B2AA' },
    NT_TEX_DIGITS: { name: 'Tex Digits', color: '#20B2AA' },
    NT_TEX_DIRT: { name: 'Tex Dirt', color: '#20B2AA' },
    NT_TEX_DPDU: { name: 'Tex Dpdu', color: '#20B2AA' },
    NT_TEX_DPDV: { name: 'Tex Dpdv', color: '#20B2AA' },
    NT_TEX_FALLOFF: { name: 'Tex Falloff', color: '#20B2AA' },
    NT_TEX_FAN_SPIRAL: { name: 'Tex Fan Spiral', color: '#20B2AA' },
    NT_TEX_FBM_FLOW_NOISE: { name: 'Tex Fbm Flow Noise', color: '#20B2AA' },
    NT_TEX_FBM_NOISE: { name: 'Tex Fbm Noise', color: '#20B2AA' },
    NT_TEX_FIELD_ANGULAR: { name: 'Tex Field Angular', color: '#20B2AA' },
    NT_TEX_FIELD_PLANAR: { name: 'Tex Field Planar', color: '#20B2AA' },
    NT_TEX_FIELD_SHAPE: { name: 'Tex Field Shape', color: '#20B2AA' },
    NT_TEX_FIELD_SPHERICAL: { name: 'Tex Field Spherical', color: '#20B2AA' },
    NT_TEX_FLAKES: { name: 'Tex Flakes', color: '#20B2AA' },
    NT_TEX_FLOAT: { name: 'Tex Float', color: '#20B2AA' },
    NT_TEX_FLOAT3_TO_COLOR: { name: 'Tex Float3 To Color', color: '#20B2AA' },
    NT_TEX_FLOATIMAGE: { name: 'Tex Floatimage', color: '#20B2AA' },
    NT_TEX_FLOATS_TO_COLOR: { name: 'Tex Floats To Color', color: '#20B2AA' },
    NT_TEX_FLOAT_TO_GREYSCALE: { name: 'Tex Float To Greyscale', color: '#20B2AA' },
    NT_TEX_FLOAT_VERTEXATTRIBUTE: { name: 'Tex Float Vertexattribute', color: '#20B2AA' },
    NT_TEX_FRACTAL: { name: 'Tex Fractal', color: '#20B2AA' },
    NT_TEX_FRACTAL_FLOW_NOISE: { name: 'Tex Fractal Flow Noise', color: '#20B2AA' },
    NT_TEX_FRACTAL_NOISE: { name: 'Tex Fractal Noise', color: '#20B2AA' },
    NT_TEX_GAUSSIANSPECTRUM: { name: 'Tex Gaussianspectrum', color: '#20B2AA' },
    NT_TEX_GLOWING_CIRCLE: { name: 'Tex Glowing Circle', color: '#20B2AA' },
    NT_TEX_GRADIENT: { name: 'Tex Gradient', color: '#20B2AA' },
    NT_TEX_GRADIENT_GENERATOR: { name: 'Tex Gradient Generator', color: '#20B2AA' },
    NT_TEX_HAGELSLAG: { name: 'Tex Hagelslag', color: '#20B2AA' },
    NT_TEX_HALFTONE: { name: 'Tex Halftone', color: '#20B2AA' },
    NT_TEX_IMAGE: { name: 'Tex Image', color: '#20B2AA' },
    NT_TEX_IMAGE_ADJUSTMENT: { name: 'Tex Image Adjustment', color: '#20B2AA' },
    NT_TEX_IMAGE_TILES: { name: 'Tex Image Tiles', color: '#20B2AA' },
    NT_TEX_IMAGE_TILE_SET: { name: 'Tex Image Tile Set', color: '#20B2AA' },
    NT_TEX_INSTANCE_COLOR: { name: 'Tex Instance Color', color: '#20B2AA' },
    NT_TEX_INSTANCE_HIGHLIGHT: { name: 'Tex Instance Highlight', color: '#20B2AA' },
    NT_TEX_INSTANCE_RANGE: { name: 'Tex Instance Range', color: '#20B2AA' },
    NT_TEX_INVERT: { name: 'Tex Invert', color: '#20B2AA' },
    NT_TEX_IRIDESCENT: { name: 'Tex Iridescent', color: '#20B2AA' },
    NT_TEX_JITTERED_COLOR_CORRECTION: { name: 'Tex Jittered Color Correction', color: '#20B2AA' },
    NT_TEX_LIGHT_FIELD_ARRAY: { name: 'Tex Light Field Array', color: '#20B2AA' },
    NT_TEX_LIGHT_FIELD_CUBE: { name: 'Tex Light Field Cube', color: '#20B2AA' },
    NT_TEX_LIGHT_FIELD_PLANE: { name: 'Tex Light Field Plane', color: '#20B2AA' },
    NT_TEX_MANDELBULB: { name: 'Tex Mandelbulb', color: '#20B2AA' },
    NT_TEX_MARBLE: { name: 'Tex Marble', color: '#20B2AA' },
    NT_TEX_MATH_BINARY: { name: 'Tex Math Binary', color: '#20B2AA' },
    NT_TEX_MATH_UNARY: { name: 'Tex Math Unary', color: '#20B2AA' },
    NT_TEX_MATRIX: { name: 'Tex Matrix', color: '#20B2AA' },
    NT_TEX_MATRIX_VALUE: { name: 'Tex Matrix Value', color: '#20B2AA' },
    NT_TEX_MIX: { name: 'Tex Mix', color: '#20B2AA' },
    NT_TEX_MOIRE_MOSAIC: { name: 'Tex Moire Mosaic', color: '#20B2AA' },
    NT_TEX_MULTIPLY: { name: 'Tex Multiply', color: '#20B2AA' },
    NT_TEX_MX_ABSVAL: { name: 'Tex Mx Absval', color: '#20B2AA' },
    NT_TEX_MX_ACOS: { name: 'Tex Mx Acos', color: '#20B2AA' },
    NT_TEX_MX_ADD: { name: 'Tex Mx Add', color: '#20B2AA' },
    NT_TEX_MX_AND: { name: 'Tex Mx And', color: '#20B2AA' },
    NT_TEX_MX_ASIN: { name: 'Tex Mx Asin', color: '#20B2AA' },
    NT_TEX_MX_ATAN2: { name: 'Tex Mx Atan2', color: '#20B2AA' },
    NT_TEX_MX_BITANGENT: { name: 'Tex Mx Bitangent', color: '#20B2AA' },
    NT_TEX_MX_BUMP: { name: 'Tex Mx Bump', color: '#20B2AA' },
    NT_TEX_MX_BURN: { name: 'Tex Mx Burn', color: '#20B2AA' },
    NT_TEX_MX_CEIL: { name: 'Tex Mx Ceil', color: '#20B2AA' },
    NT_TEX_MX_CELLNOISE2D: { name: 'Tex Mx Cellnoise2d', color: '#20B2AA' },
    NT_TEX_MX_CELLNOISE3D: { name: 'Tex Mx Cellnoise3d', color: '#20B2AA' },
    NT_TEX_MX_CLAMP: { name: 'Tex Mx Clamp', color: '#20B2AA' },
    NT_TEX_MX_COLORCORRECT: { name: 'Tex Mx Colorcorrect', color: '#20B2AA' },
    NT_TEX_MX_COMBINE2: { name: 'Tex Mx Combine2', color: '#20B2AA' },
    NT_TEX_MX_COMBINE2_COLOR3FLOAT: { name: 'Tex Mx Combine2 Color3float', color: '#20B2AA' },
    NT_TEX_MX_COMBINE2_VECTOR2FLOAT: { name: 'Tex Mx Combine2 Vector2float', color: '#20B2AA' },
    NT_TEX_MX_COMBINE2_VECTOR2VECTOR2: { name: 'Tex Mx Combine2 Vector2vector2', color: '#20B2AA' },
    NT_TEX_MX_COMBINE2_VECTOR3FLOAT: { name: 'Tex Mx Combine2 Vector3float', color: '#20B2AA' },
    NT_TEX_MX_COMBINE3: { name: 'Tex Mx Combine3', color: '#20B2AA' },
    NT_TEX_MX_COMBINE4: { name: 'Tex Mx Combine4', color: '#20B2AA' },
    NT_TEX_MX_CONSTANT: { name: 'Tex Mx Constant', color: '#20B2AA' },
    NT_TEX_MX_CONTRAST: { name: 'Tex Mx Contrast', color: '#20B2AA' },
    NT_TEX_MX_CONVERT: { name: 'Tex Mx Convert', color: '#20B2AA' },
    NT_TEX_MX_COS: { name: 'Tex Mx Cos', color: '#20B2AA' },
    NT_TEX_MX_CREATEMATRIX: { name: 'Tex Mx Creatematrix', color: '#20B2AA' },
    NT_TEX_MX_CREATEMATRIX3X3: { name: 'Tex Mx Creatematrix3x3', color: '#20B2AA' },
    NT_TEX_MX_CROSSPRODUCT: { name: 'Tex Mx Crossproduct', color: '#20B2AA' },
    NT_TEX_MX_DETERMINANT: { name: 'Tex Mx Determinant', color: '#20B2AA' },
    NT_TEX_MX_DIFFERENCE: { name: 'Tex Mx Difference', color: '#20B2AA' },
    NT_TEX_MX_DISJOINTOVER: { name: 'Tex Mx Disjointover', color: '#20B2AA' },
    NT_TEX_MX_DISTANCE: { name: 'Tex Mx Distance', color: '#20B2AA' },
    NT_TEX_MX_DIVIDE: { name: 'Tex Mx Divide', color: '#20B2AA' },
    NT_TEX_MX_DODGE: { name: 'Tex Mx Dodge', color: '#20B2AA' },
    NT_TEX_MX_DOTPRODUCT: { name: 'Tex Mx Dotproduct', color: '#20B2AA' },
    NT_TEX_MX_EXP: { name: 'Tex Mx Exp', color: '#20B2AA' },
    NT_TEX_MX_EXTRACT2: { name: 'Tex Mx Extract2', color: '#20B2AA' },
    NT_TEX_MX_EXTRACT3: { name: 'Tex Mx Extract3', color: '#20B2AA' },
    NT_TEX_MX_EXTRACT4: { name: 'Tex Mx Extract4', color: '#20B2AA' },
    NT_TEX_MX_FACINGRATIO: { name: 'Tex Mx Facingratio', color: '#20B2AA' },
    NT_TEX_MX_FLOOR: { name: 'Tex Mx Floor', color: '#20B2AA' },
    NT_TEX_MX_FRACT: { name: 'Tex Mx Fract', color: '#20B2AA' },
    NT_TEX_MX_FRACTAL3D: { name: 'Tex Mx Fractal3d', color: '#20B2AA' },
    NT_TEX_MX_FRAME: { name: 'Tex Mx Frame', color: '#20B2AA' },
    NT_TEX_MX_GEOMCOLOR: { name: 'Tex Mx Geomcolor', color: '#20B2AA' },
    NT_TEX_MX_GEOMPROPVALUE: { name: 'Tex Mx Geompropvalue', color: '#20B2AA' },
    NT_TEX_MX_HEIGHTTONORMAL: { name: 'Tex Mx Heighttonormal', color: '#20B2AA' },
    NT_TEX_MX_HSVADJUST: { name: 'Tex Mx Hsvadjust', color: '#20B2AA' },
    NT_TEX_MX_HSVTORGB: { name: 'Tex Mx Hsvtorgb', color: '#20B2AA' },
    NT_TEX_MX_IFEQUAL: { name: 'Tex Mx Ifequal', color: '#20B2AA' },
    NT_TEX_MX_IFEQUAL_B: { name: 'Tex Mx Ifequal B', color: '#20B2AA' },
    NT_TEX_MX_IFEQUAL_BOOL: { name: 'Tex Mx Ifequal Bool', color: '#20B2AA' },
    NT_TEX_MX_IFGREATER: { name: 'Tex Mx Ifgreater', color: '#20B2AA' },
    NT_TEX_MX_IFGREATEREQ: { name: 'Tex Mx Ifgreatereq', color: '#20B2AA' },
    NT_TEX_MX_IFGREATEREQ_BOOL: { name: 'Tex Mx Ifgreatereq Bool', color: '#20B2AA' },
    NT_TEX_MX_IFGREATER_BOOL: { name: 'Tex Mx Ifgreater Bool', color: '#20B2AA' },
    NT_TEX_MX_IMAGE: { name: 'Tex Mx Image', color: '#20B2AA' },
    NT_TEX_MX_IN: { name: 'Tex Mx In', color: '#20B2AA' },
    NT_TEX_MX_INSIDE: { name: 'Tex Mx Inside', color: '#20B2AA' },
    NT_TEX_MX_INVERT: { name: 'Tex Mx Invert', color: '#20B2AA' },
    NT_TEX_MX_INVERTMATRIX: { name: 'Tex Mx Invertmatrix', color: '#20B2AA' },
    NT_TEX_MX_LN: { name: 'Tex Mx Ln', color: '#20B2AA' },
    NT_TEX_MX_LUMINANCE: { name: 'Tex Mx Luminance', color: '#20B2AA' },
    NT_TEX_MX_MAGNITUDE: { name: 'Tex Mx Magnitude', color: '#20B2AA' },
    NT_TEX_MX_MASK: { name: 'Tex Mx Mask', color: '#20B2AA' },
    NT_TEX_MX_MATTE: { name: 'Tex Mx Matte', color: '#20B2AA' },
    NT_TEX_MX_MAX: { name: 'Tex Mx Max', color: '#20B2AA' },
    NT_TEX_MX_MIN: { name: 'Tex Mx Min', color: '#20B2AA' },
    NT_TEX_MX_MINUS: { name: 'Tex Mx Minus', color: '#20B2AA' },
    NT_TEX_MX_MIX: { name: 'Tex Mx Mix', color: '#20B2AA' },
    NT_TEX_MX_MODULO: { name: 'Tex Mx Modulo', color: '#20B2AA' },
    NT_TEX_MX_MULTIPLY: { name: 'Tex Mx Multiply', color: '#20B2AA' },
    NT_TEX_MX_NOISE2D: { name: 'Tex Mx Noise2d', color: '#20B2AA' },
    NT_TEX_MX_NOISE3D: { name: 'Tex Mx Noise3d', color: '#20B2AA' },
    NT_TEX_MX_NORMAL: { name: 'Tex Mx Normal', color: '#20B2AA' },
    NT_TEX_MX_NORMALIZE: { name: 'Tex Mx Normalize', color: '#20B2AA' },
    NT_TEX_MX_NORMALMAP: { name: 'Tex Mx Normalmap', color: '#20B2AA' },
    NT_TEX_MX_NOT: { name: 'Tex Mx Not', color: '#20B2AA' },
    NT_TEX_MX_OR: { name: 'Tex Mx Or', color: '#20B2AA' },
    NT_TEX_MX_OUT: { name: 'Tex Mx Out', color: '#20B2AA' },
    NT_TEX_MX_OUTSIDE: { name: 'Tex Mx Outside', color: '#20B2AA' },
    NT_TEX_MX_OVER: { name: 'Tex Mx Over', color: '#20B2AA' },
    NT_TEX_MX_OVERLAY: { name: 'Tex Mx Overlay', color: '#20B2AA' },
    NT_TEX_MX_PLACE2D: { name: 'Tex Mx Place2d', color: '#20B2AA' },
    NT_TEX_MX_PLUS: { name: 'Tex Mx Plus', color: '#20B2AA' },
    NT_TEX_MX_POSITION: { name: 'Tex Mx Position', color: '#20B2AA' },
    NT_TEX_MX_POWER: { name: 'Tex Mx Power', color: '#20B2AA' },
    NT_TEX_MX_PREMULT: { name: 'Tex Mx Premult', color: '#20B2AA' },
    NT_TEX_MX_RAMP4: { name: 'Tex Mx Ramp4', color: '#20B2AA' },
    NT_TEX_MX_RAMPLR: { name: 'Tex Mx Ramplr', color: '#20B2AA' },
    NT_TEX_MX_RAMPTB: { name: 'Tex Mx Ramptb', color: '#20B2AA' },
    NT_TEX_MX_RANDOMCOLOR: { name: 'Tex Mx Randomcolor', color: '#20B2AA' },
    NT_TEX_MX_RANDOMFLOAT: { name: 'Tex Mx Randomfloat', color: '#20B2AA' },
    NT_TEX_MX_RANGE: { name: 'Tex Mx Range', color: '#20B2AA' },
    NT_TEX_MX_REFLECT: { name: 'Tex Mx Reflect', color: '#20B2AA' },
    NT_TEX_MX_REFRACT: { name: 'Tex Mx Refract', color: '#20B2AA' },
    NT_TEX_MX_REMAP: { name: 'Tex Mx Remap', color: '#20B2AA' },
    NT_TEX_MX_RGBTOHSV: { name: 'Tex Mx Rgbtohsv', color: '#20B2AA' },
    NT_TEX_MX_ROTATE2D: { name: 'Tex Mx Rotate2d', color: '#20B2AA' },
    NT_TEX_MX_ROTATE3D: { name: 'Tex Mx Rotate3d', color: '#20B2AA' },
    NT_TEX_MX_ROUND: { name: 'Tex Mx Round', color: '#20B2AA' },
    NT_TEX_MX_SAFEPOWER: { name: 'Tex Mx Safepower', color: '#20B2AA' },
    NT_TEX_MX_SATURATE: { name: 'Tex Mx Saturate', color: '#20B2AA' },
    NT_TEX_MX_SCREEN: { name: 'Tex Mx Screen', color: '#20B2AA' },
    NT_TEX_MX_SEPARATE2: { name: 'Tex Mx Separate2', color: '#20B2AA' },
    NT_TEX_MX_SEPARATE3: { name: 'Tex Mx Separate3', color: '#20B2AA' },
    NT_TEX_MX_SEPARATE4: { name: 'Tex Mx Separate4', color: '#20B2AA' },
    NT_TEX_MX_SIGN: { name: 'Tex Mx Sign', color: '#20B2AA' },
    NT_TEX_MX_SIN: { name: 'Tex Mx Sin', color: '#20B2AA' },
    NT_TEX_MX_SMOOTHSTEP: { name: 'Tex Mx Smoothstep', color: '#20B2AA' },
    NT_TEX_MX_SPLITLR: { name: 'Tex Mx Splitlr', color: '#20B2AA' },
    NT_TEX_MX_SPLITTB: { name: 'Tex Mx Splittb', color: '#20B2AA' },
    NT_TEX_MX_SQRT: { name: 'Tex Mx Sqrt', color: '#20B2AA' },
    NT_TEX_MX_SUBTRACT: { name: 'Tex Mx Subtract', color: '#20B2AA' },
    NT_TEX_MX_SWITCH: { name: 'Tex Mx Switch', color: '#20B2AA' },
    NT_TEX_MX_TAN: { name: 'Tex Mx Tan', color: '#20B2AA' },
    NT_TEX_MX_TANGENT: { name: 'Tex Mx Tangent', color: '#20B2AA' },
    NT_TEX_MX_TEXCOORD: { name: 'Tex Mx Texcoord', color: '#20B2AA' },
    NT_TEX_MX_TILEDIMAGE: { name: 'Tex Mx Tiledimage', color: '#20B2AA' },
    NT_TEX_MX_TIME: { name: 'Tex Mx Time', color: '#20B2AA' },
    NT_TEX_MX_TRANSFORMMATRIX: { name: 'Tex Mx Transformmatrix', color: '#20B2AA' },
    NT_TEX_MX_TRANSFORMMATRIX3X3: { name: 'Tex Mx Transformmatrix3x3', color: '#20B2AA' },
    NT_TEX_MX_TRANSFORMNORMAL: { name: 'Tex Mx Transformnormal', color: '#20B2AA' },
    NT_TEX_MX_TRANSFORMPOINT: { name: 'Tex Mx Transformpoint', color: '#20B2AA' },
    NT_TEX_MX_TRANSFORMVECTOR: { name: 'Tex Mx Transformvector', color: '#20B2AA' },
    NT_TEX_MX_TRANSPOSE: { name: 'Tex Mx Transpose', color: '#20B2AA' },
    NT_TEX_MX_TRIANGLEWAVE: { name: 'Tex Mx Trianglewave', color: '#20B2AA' },
    NT_TEX_MX_TRIPLANARPROJECTION: { name: 'Tex Mx Triplanarprojection', color: '#20B2AA' },
    NT_TEX_MX_UNPREMULT: { name: 'Tex Mx Unpremult', color: '#20B2AA' },
    NT_TEX_MX_UPDIRECTION: { name: 'Tex Mx Updirection', color: '#20B2AA' },
    NT_TEX_MX_VIEWDIRECTION: { name: 'Tex Mx Viewdirection', color: '#20B2AA' },
    NT_TEX_MX_WORLEYNOISE2D: { name: 'Tex Mx Worleynoise2d', color: '#20B2AA' },
    NT_TEX_MX_WORLEYNOISE3D: { name: 'Tex Mx Worleynoise3d', color: '#20B2AA' },
    NT_TEX_MX_XOR: { name: 'Tex Mx Xor', color: '#20B2AA' },
    NT_TEX_NOISE: { name: 'Tex Noise', color: '#20B2AA' },
    NT_TEX_NORMAL: { name: 'Tex Normal', color: '#20B2AA' },
    NT_TEX_OBJECT_LAYER_COLOR: { name: 'Tex Object Layer Color', color: '#20B2AA' },
    NT_TEX_OSL: { name: 'Tex Osl', color: '#20B2AA' },
    NT_TEX_OUTPUT_AOV_PARAMETER: { name: 'Tex Output Aov Parameter', color: '#20B2AA' },
    NT_TEX_PIXEL_FLOW: { name: 'Tex Pixel Flow', color: '#20B2AA' },
    NT_TEX_POSITION: { name: 'Tex Position', color: '#20B2AA' },
    NT_TEX_PROCEDURAL_EFFECTS: { name: 'Tex Procedural Effects', color: '#20B2AA' },
    NT_TEX_RAIN_BUMP: { name: 'Tex Rain Bump', color: '#20B2AA' },
    NT_TEX_RANDOMCOLOR: { name: 'Tex Randomcolor', color: '#20B2AA' },
    NT_TEX_RANDOM_MAP: { name: 'Tex Random Map', color: '#20B2AA' },
    NT_TEX_RANGE: { name: 'Tex Range', color: '#20B2AA' },
    NT_TEX_RAY_DIRECTION: { name: 'Tex Ray Direction', color: '#20B2AA' },
    NT_TEX_RAY_SWITCH: { name: 'Tex Ray Switch', color: '#20B2AA' },
    NT_TEX_READ_VDB: { name: 'Tex Read Vdb', color: '#20B2AA' },
    NT_TEX_RELATIVE_DISTANCE: { name: 'Tex Relative Distance', color: '#20B2AA' },
    NT_TEX_RGB: { name: 'Tex Rgb', color: '#20B2AA' },
    NT_TEX_RGBA: { name: 'Tex Rgba', color: '#20B2AA' },
    NT_TEX_RGFRACTAL: { name: 'Tex Rgfractal', color: '#20B2AA' },
    NT_TEX_ROT_FRACTAL: { name: 'Tex Rot Fractal', color: '#20B2AA' },
    NT_TEX_SAMPLE_POSITION: { name: 'Tex Sample Position', color: '#20B2AA' },
    NT_TEX_SAWWAVE: { name: 'Tex Sawwave', color: '#20B2AA' },
    NT_TEX_SCRATCHES: { name: 'Tex Scratches', color: '#20B2AA' },
    NT_TEX_SIDE: { name: 'Tex Side', color: '#20B2AA' },
    NT_TEX_SINEWAVE: { name: 'Tex Sinewave', color: '#20B2AA' },
    NT_TEX_SINE_WAVE_FAN: { name: 'Tex Sine Wave Fan', color: '#20B2AA' },
    NT_TEX_SNOW: { name: 'Tex Snow', color: '#20B2AA' },
    NT_TEX_SPOTLIGHT: { name: 'Tex Spotlight', color: '#20B2AA' },
    NT_TEX_STAR_FIELD: { name: 'Tex Star Field', color: '#20B2AA' },
    NT_TEX_STRIPES: { name: 'Tex Stripes', color: '#20B2AA' },
    NT_TEX_SUBTRACT: { name: 'Tex Subtract', color: '#20B2AA' },
    NT_TEX_TILE_PATTERNS: { name: 'Tex Tile Patterns', color: '#20B2AA' },
    NT_TEX_TRANSFORMED_UV: { name: 'Tex Transformed Uv', color: '#20B2AA' },
    NT_TEX_TRANSFORM_TO_MATRIX: { name: 'Tex Transform To Matrix', color: '#20B2AA' },
    NT_TEX_TRIANGLEWAVE: { name: 'Tex Trianglewave', color: '#20B2AA' },
    NT_TEX_TRIPLANAR: { name: 'Tex Triplanar', color: '#20B2AA' },
    NT_TEX_TRIPPER: { name: 'Tex Tripper', color: '#20B2AA' },
    NT_TEX_TURBULENCE: { name: 'Tex Turbulence', color: '#20B2AA' },
    NT_TEX_UV: { name: 'Tex Uv', color: '#20B2AA' },
    NT_TEX_UVW_TRANSFORM: { name: 'Tex Uvw Transform', color: '#20B2AA' },
    NT_TEX_VOLUME_CLOUD: { name: 'Tex Volume Cloud', color: '#20B2AA' },
    NT_TEX_VORONOI_SMOOTH_CONTOURS: { name: 'Tex Voronoi Smooth Contours', color: '#20B2AA' },
    NT_TEX_W: { name: 'Tex W', color: '#20B2AA' },
    NT_TEX_WAVE_PATTERN: { name: 'Tex Wave Pattern', color: '#20B2AA' },
    NT_TEX_WOODGRAIN: { name: 'Tex Woodgrain', color: '#20B2AA' },
    NT_TEX_Z_DEPTH: { name: 'Tex Z Depth', color: '#20B2AA' },
  },
  Transforms: {
    NT_SUN_DIRECTION: { name: 'Sun Direction', color: '#DC143C' },
    NT_TRANSFORM_2D: { name: 'Transform 2d', color: '#DC143C' },
    NT_TRANSFORM_2D_FROM_UV: { name: 'Transform 2d From Uv', color: '#DC143C' },
    NT_TRANSFORM_3D: { name: 'Transform 3d', color: '#DC143C' },
    NT_TRANSFORM_LOOKAT: { name: 'Transform Lookat', color: '#DC143C' },
    NT_TRANSFORM_ROTATION: { name: 'Transform Rotation', color: '#DC143C' },
    NT_TRANSFORM_SCALE: { name: 'Transform Scale', color: '#DC143C' },
    NT_TRANSFORM_VALUE: { name: 'Transform Value', color: '#DC143C' },
  },
  Values: {
    NT_BIT_MASK: { name: 'Bit Mask', color: '#7B68EE' },
    NT_LUT_CUSTOM: { name: 'Lut Custom', color: '#7B68EE' },
    NT_OBJECTLAYER: { name: 'Objectlayer', color: '#7B68EE' },
    NT_OBJECTLAYER_MAP: { name: 'Objectlayer Map', color: '#7B68EE' },
    NT_OCIO_COLOR_SPACE: { name: 'Ocio Color Space', color: '#7B68EE' },
    NT_OCIO_LOOK: { name: 'Ocio Look', color: '#7B68EE' },
    NT_OCIO_VIEW: { name: 'Ocio View', color: '#7B68EE' },
    NT_TOON_RAMP: { name: 'Toon Ramp', color: '#7B68EE' },
    NT_TRACE_SET_VISIBILITY_RULE: { name: 'Trace Set Visibility Rule', color: '#7B68EE' },
    NT_TRACE_SET_VISIBILITY_RULE_GROUP: {
      name: 'Trace Set Visibility Rule Group',
      color: '#7B68EE',
    },
    NT_VOLUME_RAMP: { name: 'Volume Ramp', color: '#7B68EE' },
  },
  'Node graph': {
    NT_IN_ANIMATION_SETTINGS: { name: 'In Animation Settings', color: '#9370DB' },
    NT_IN_BIT_MASK: { name: 'In Bit Mask', color: '#9370DB' },
    NT_IN_BLENDING_SETTINGS: { name: 'In Blending Settings', color: '#9370DB' },
    NT_IN_BOOL: { name: 'In Bool', color: '#9370DB' },
    NT_IN_CAMERA: { name: 'In Camera', color: '#9370DB' },
    NT_IN_DISPLACEMENT: { name: 'In Displacement', color: '#9370DB' },
    NT_IN_EMISSION: { name: 'In Emission', color: '#9370DB' },
    NT_IN_ENUM: { name: 'In Enum', color: '#9370DB' },
    NT_IN_ENVIRONMENT: { name: 'In Environment', color: '#9370DB' },
    NT_IN_FILM_SETTINGS: { name: 'In Film Settings', color: '#9370DB' },
    NT_IN_FLOAT: { name: 'In Float', color: '#9370DB' },
    NT_IN_GEOMETRY: { name: 'In Geometry', color: '#9370DB' },
    NT_IN_IMAGER: { name: 'In Imager', color: '#9370DB' },
    NT_IN_INT: { name: 'In Int', color: '#9370DB' },
    NT_IN_KERNEL: { name: 'In Kernel', color: '#9370DB' },
    NT_IN_LUT: { name: 'In Lut', color: '#9370DB' },
    NT_IN_MATERIAL: { name: 'In Material', color: '#9370DB' },
    NT_IN_MATERIAL_LAYER: { name: 'In Material Layer', color: '#9370DB' },
    NT_IN_MEDIUM: { name: 'In Medium', color: '#9370DB' },
    NT_IN_OBJECTLAYER: { name: 'In Objectlayer', color: '#9370DB' },
    NT_IN_OCIO_COLOR_SPACE: { name: 'In Ocio Color Space', color: '#9370DB' },
    NT_IN_OCIO_LOOK: { name: 'In Ocio Look', color: '#9370DB' },
    NT_IN_OCIO_VIEW: { name: 'In Ocio View', color: '#9370DB' },
    NT_IN_OFFSET: { name: 'In Offset', color: '#9370DB' },
    NT_IN_OUTPUT_AOV: { name: 'In Output Aov', color: '#9370DB' },
    NT_IN_OUTPUT_AOV_GROUP: { name: 'In Output Aov Group', color: '#9370DB' },
    NT_IN_OUTPUT_AOV_LAYER: { name: 'In Output Aov Layer', color: '#9370DB' },
    NT_IN_PHASEFUNCTION: { name: 'In Phasefunction', color: '#9370DB' },
    NT_IN_POSTPROCESSING: { name: 'In Postprocessing', color: '#9370DB' },
    NT_IN_POST_VOLUME: { name: 'In Post Volume', color: '#9370DB' },
    NT_IN_PROJECTION: { name: 'In Projection', color: '#9370DB' },
    NT_IN_RENDERTARGET: { name: 'In Rendertarget', color: '#9370DB' },
    NT_IN_RENDER_JOB: { name: 'In Render Job', color: '#9370DB' },
    NT_IN_RENDER_LAYER: { name: 'In Render Layer', color: '#9370DB' },
    NT_IN_RENDER_PASSES: { name: 'In Render Passes', color: '#9370DB' },
    NT_IN_ROUND_EDGES: { name: 'In Round Edges', color: '#9370DB' },
    NT_IN_STRING: { name: 'In String', color: '#9370DB' },
    NT_IN_TEXTURE: { name: 'In Texture', color: '#9370DB' },
    NT_IN_TEX_COMPOSITE_LAYER: { name: 'In Tex Composite Layer', color: '#9370DB' },
    NT_IN_TOON_RAMP: { name: 'In Toon Ramp', color: '#9370DB' },
    NT_IN_TRACE_SET_VISIBILITY_RULE: { name: 'In Trace Set Visibility Rule', color: '#9370DB' },
    NT_IN_TRACE_SET_VISIBILITY_RULE_GROUP: {
      name: 'In Trace Set Visibility Rule Group',
      color: '#9370DB',
    },
    NT_IN_TRANSFORM: { name: 'In Transform', color: '#9370DB' },
    NT_IN_VOLUME_RAMP: { name: 'In Volume Ramp', color: '#9370DB' },
    NT_SWITCH_ANIMATION_SETTINGS: { name: 'Switch Animation Settings', color: '#9370DB' },
    NT_SWITCH_BIT_MASK: { name: 'Switch Bit Mask', color: '#9370DB' },
    NT_SWITCH_BLENDING_SETTINGS: { name: 'Switch Blending Settings', color: '#9370DB' },
    NT_SWITCH_BOOL: { name: 'Switch Bool', color: '#9370DB' },
    NT_SWITCH_CAMERA: { name: 'Switch Camera', color: '#9370DB' },
    NT_SWITCH_DISPLACEMENT: { name: 'Switch Displacement', color: '#9370DB' },
    NT_SWITCH_EMISSION: { name: 'Switch Emission', color: '#9370DB' },
    NT_SWITCH_ENUM: { name: 'Switch Enum', color: '#9370DB' },
    NT_SWITCH_ENVIRONMENT: { name: 'Switch Environment', color: '#9370DB' },
    NT_SWITCH_FILM_SETTINGS: { name: 'Switch Film Settings', color: '#9370DB' },
    NT_SWITCH_FLOAT: { name: 'Switch Float', color: '#9370DB' },
    NT_SWITCH_GEOMETRY: { name: 'Switch Geometry', color: '#9370DB' },
    NT_SWITCH_IMAGER: { name: 'Switch Imager', color: '#9370DB' },
    NT_SWITCH_INT: { name: 'Switch Int', color: '#9370DB' },
    NT_SWITCH_INTERNAL: { name: 'Switch Internal', color: '#9370DB' },
    NT_SWITCH_KERNEL: { name: 'Switch Kernel', color: '#9370DB' },
    NT_SWITCH_LUT: { name: 'Switch Lut', color: '#9370DB' },
    NT_SWITCH_MATERIAL: { name: 'Switch Material', color: '#9370DB' },
    NT_SWITCH_MATERIAL_LAYER: { name: 'Switch Material Layer', color: '#9370DB' },
    NT_SWITCH_MEDIUM: { name: 'Switch Medium', color: '#9370DB' },
    NT_SWITCH_OBJECTLAYER: { name: 'Switch Objectlayer', color: '#9370DB' },
    NT_SWITCH_OCIO_COLOR_SPACE: { name: 'Switch Ocio Color Space', color: '#9370DB' },
    NT_SWITCH_OCIO_LOOK: { name: 'Switch Ocio Look', color: '#9370DB' },
    NT_SWITCH_OCIO_VIEW: { name: 'Switch Ocio View', color: '#9370DB' },
    NT_SWITCH_OFFSET: { name: 'Switch Offset', color: '#9370DB' },
    NT_SWITCH_OUTPUT_AOV: { name: 'Switch Output Aov', color: '#9370DB' },
    NT_SWITCH_OUTPUT_AOV_GROUP: { name: 'Switch Output Aov Group', color: '#9370DB' },
    NT_SWITCH_OUTPUT_AOV_LAYER: { name: 'Switch Output Aov Layer', color: '#9370DB' },
    NT_SWITCH_PHASEFUNCTION: { name: 'Switch Phasefunction', color: '#9370DB' },
    NT_SWITCH_POSTPROCESSING: { name: 'Switch Postprocessing', color: '#9370DB' },
    NT_SWITCH_POST_VOLUME: { name: 'Switch Post Volume', color: '#9370DB' },
    NT_SWITCH_PROJECTION: { name: 'Switch Projection', color: '#9370DB' },
    NT_SWITCH_RENDERTARGET: { name: 'Switch Rendertarget', color: '#9370DB' },
    NT_SWITCH_RENDER_JOB: { name: 'Switch Render Job', color: '#9370DB' },
    NT_SWITCH_RENDER_LAYER: { name: 'Switch Render Layer', color: '#9370DB' },
    NT_SWITCH_RENDER_PASSES: { name: 'Switch Render Passes', color: '#9370DB' },
    NT_SWITCH_ROUND_EDGES: { name: 'Switch Round Edges', color: '#9370DB' },
    NT_SWITCH_STRING: { name: 'Switch String', color: '#9370DB' },
    NT_SWITCH_TEXTURE: { name: 'Switch Texture', color: '#9370DB' },
    NT_SWITCH_TEX_COMPOSITE_LAYER: { name: 'Switch Tex Composite Layer', color: '#9370DB' },
    NT_SWITCH_TOON_RAMP: { name: 'Switch Toon Ramp', color: '#9370DB' },
    NT_SWITCH_TRACE_SET_VISIBILITY_RULE: {
      name: 'Switch Trace Set Visibility Rule',
      color: '#9370DB',
    },
    NT_SWITCH_TRACE_SET_VISIBILITY_RULE_GROUP: {
      name: 'Switch Trace Set Visibility Rule Group',
      color: '#9370DB',
    },
    NT_SWITCH_TRANSFORM: { name: 'Switch Transform', color: '#9370DB' },
    NT_SWITCH_VOLUME_RAMP: { name: 'Switch Volume Ramp', color: '#9370DB' },
  },
  'Render target': {
    NT_RENDERTARGET: { name: 'Rendertarget', color: '#FFA07A' },
  },
};

/**
 * Category display order matching Octane's context menu
 * '___SEPARATOR___' indicates a visual separator line
 */
export const CATEGORY_ORDER: string[] = [
  'Cameras',
  'Displacement',
  'Emission',
  'Environments',
  'Geometry',
  'Input',
  'Kernels',
  'Lights',
  'Material layers',
  'Materials',
  'Medium',
  'Other',
  'Output',
  'Output AOVs',
  'Projection',
  'Render AOVs',
  'Render job',
  'Render settings',
  'Round edges',
  'Texture layers',
  'Textures',
  'Transforms',
  'Values',
  '___SEPARATOR___',
  'Node graph',
  'Render target',
];

/**
 * Get all categories
 */
export function getNodeCategories(): string[] {
  return Object.keys(OCTANE_NODE_TYPES);
}

/**
 * Get categories in display order (with separators)
 */
export function getCategoriesInOrder(): string[] {
  return CATEGORY_ORDER;
}

/**
 * Get node types for a specific category
 */
export function getNodeTypesForCategory(category: string): NodeTypeCategory | undefined {
  return OCTANE_NODE_TYPES[category];
}

/**
 * Get node type info
 */
export function getNodeTypeInfo(nodeType: string): NodeTypeInfo | undefined {
  for (const category of Object.values(OCTANE_NODE_TYPES)) {
    if (category[nodeType]) {
      return category[nodeType];
    }
  }
  return undefined;
}

/**
 * Get all node types as a flat list
 */
export function getAllNodeTypes(): string[] {
  const allTypes: string[] = [];
  for (const category of Object.values(OCTANE_NODE_TYPES)) {
    allTypes.push(...Object.keys(category));
  }
  return allTypes.sort();
}

/**
 * Icon Mapping Interface
 * Maps node types to their icon filenames
 */
export interface IconMapping {
  [nodeType: string]: string;
}

/**
 * Complete mapping of NT_ node types to icon filenames
 * Icons are extracted from the actual Octane UI and named descriptively.
 *
 * Note: Not all NT_ types have unique icons - many share the same icon with other nodes of similar type.
 */
export const nodeIconMapping: IconMapping = {
  // Cameras
  NT_CAM_BAKING: 'BAKING_CAMERA node.png',
  NT_CAM_OSL: 'OSL_BAKING_CAMERA node.png',
  NT_CAM_OSL_BAKING: 'OSL_BAKING_CAMERA node.png',
  NT_CAM_PANORAMIC: 'PANORAMIC_CAMERA node.png',
  NT_CAM_SIMULATED_LENS: 'SIMULATED_LENS_CAMERA node.png',
  NT_CAM_THINLENS: 'THINLENS_CAMERA node.png',
  NT_CAM_UNIVERSAL: 'CAMERA node.png',

  // Displacement
  NT_DISPLACEMENT: 'DISPLACEMENT_OUT node.png',
  NT_VERTEX_DISPLACEMENT: 'VERTEX_DISPLACEMENT node.png',
  NT_VERTEX_DISPLACEMENT_MIXER: 'VERTEX_DISPLACEMENT_MIXER node.png',

  // Emission
  NT_EMIS_BLACKBODY: 'EMITTER_BBODY node.png',
  NT_EMIS_TEXTURE: 'EMITTER_TEXTURE node.png',

  // Environments
  NT_ENV_DAYLIGHT: 'ENVIRONMENT node.png',
  NT_ENV_PLANETARY: 'ENVIRONMENT node.png',
  NT_ENV_TEXTURE: 'ENVIRONMENT node.png',

  // Geometry - Basic
  NT_GEO_DECAL: 'DECAL node.png',
  NT_GEO_EXPORTER: 'GEOMETRY_EXPORTER node.png',
  NT_GEO_GAUSSIAN_SPLAT: 'GAUSSIAN_SPLAT node.png',
  NT_GEO_GROUP: 'GEOMETRY_GROUP node.png',
  NT_GEO_JOINT: 'JOINT node.png',
  NT_GEO_MESH: 'MESH node.png',
  NT_GEO_MESH_VOLUME: 'MESH_VOLUME node.png',
  NT_GEO_MESH_VOLUME_SDF: 'MESH_VOLUME_SDF node.png',
  NT_GEO_OBJECT: 'SCENE node.png',
  NT_GEO_OSL: 'OSL_GEOMETRY node.png',
  NT_GEO_PLACEMENT: 'PLACEMENT node.png',
  NT_GEO_PLANE: 'PLANE node.png',
  NT_GEO_SCATTER: 'SCATTER node.png',

  // Geometry - SDF
  NT_GEO_SDF_ARRAY_CIRCULAR: 'SDF_ARRAY node.png',
  NT_GEO_SDF_ARRAY_LINEAR: 'SDF_ARRAY node.png',
  NT_GEO_SDF_AVOID: 'SDF_AVOID node.png',
  NT_GEO_SDF_BOX: 'SDF_BOX node.png',
  NT_GEO_SDF_CAPSULE: 'SDF_CAPSULE node.png',
  NT_GEO_SDF_CLIP: 'SDF_CLIP node.png',
  NT_GEO_SDF_CONE: 'SDF_CONE node.png',
  NT_GEO_SDF_CYLINDER: 'SDF_CYLINDER node.png',
  NT_GEO_SDF_DISPLACEMENT: 'SDF_DISPLACEMENT node.png',
  NT_GEO_SDF_DOMAIN: 'SDF_DOMAIN node.png',
  NT_GEO_SDF_INK: 'SDF_INK node.png',
  NT_GEO_SDF_INSET: 'SDF_INSET node.png',
  NT_GEO_SDF_INTERSECT: 'SDF_INTERSECT node.png',
  NT_GEO_SDF_MIRROR: 'SDF_MIRROR node.png',
  NT_GEO_SDF_OFFSET: 'SDF_OFFSET node.png',
  NT_GEO_SDF_PRISM: 'SDF_PRISM node.png',
  NT_GEO_SDF_PULL: 'SDF_PULL node.png',
  NT_GEO_SDF_PUSH: 'SDF_PUSH node.png',
  NT_GEO_SDF_REPEL: 'SDF_REPEL node.png',
  NT_GEO_SDF_SPHERE: 'SDF_SPHERE node.png',
  NT_GEO_SDF_SUBTRACT: 'SDF_SUBTRACT node.png',
  NT_GEO_SDF_TORUS: 'SDF_TORUS node.png',
  NT_GEO_SDF_TUBE: 'SDF_TUBE node.png',
  NT_GEO_SDF_UNION: 'SDF_UNION node.png',

  // Geometry - Volume
  NT_GEO_UNIT_VOLUME: 'UNIT_VOLUME node.png',
  NT_GEO_VOLUME: 'VOLUME node.png',
  NT_GEO_VOLUME_SDF: 'VOLUME_SDF node.png',
  NT_SCATTER_SURFACE: 'SCATTER_ON_SURFACE node.png',
  NT_SCATTER_VOLUME: 'SCATTER_IN_VOLUME node.png',

  // Input - Basic Types
  NT_BOOL: 'VALUE BOOL node.png',
  NT_BOOL_LOGIC_OPERATOR: 'BOOLEAN_LOGIC_OPERATOR node.png',
  NT_DIRECTORY: 'DIRECTORY_NAME node.png',
  NT_ENUM: 'VALUE INT node.png',
  NT_FILE: 'FILE_NAME node.png',
  NT_FLOAT: 'VALUE FLOAT node.png',
  NT_FLOAT_COMPONENT_MERGER: 'FLOAT_COMPONENT_MERGER node.png',
  NT_FLOAT_COMPONENT_PICKER: 'FLOAT_COMPONENT_PICKER node.png',
  NT_FLOAT_IF: 'FLOAT_IF node.png',
  NT_FLOAT_MATH_BINARY: 'BINARY_MATH_OPERATION node.png',
  NT_FLOAT_MATH_UNARY: 'UNARY_MATH_OPERATION node.png',
  NT_FLOAT_RANGE: 'MAP_RANGE node.png',
  NT_FLOAT_RELATIONAL_OPERATOR: 'FLOAT_RELATIONAL_OPERATOR node.png',
  NT_FLOAT_TIME: 'FLOAT_TIME node.png',
  NT_FLOAT_TO_INT: 'MATERIALX_CONVERT_node.png',
  NT_INT: 'VALUE INT node.png',
  NT_INT_COMPONENT_MERGER: 'INT_COMPONENT_MERGER node.png',
  NT_INT_COMPONENT_PICKER: 'INT_COMPONENT_PICKER node.png',
  NT_INT_FRAME_INDEX: 'FRAME_INDEX node.png',
  NT_INT_IF: 'INT_IF node.png',
  NT_INT_RELATIONAL_OPERATOR: 'INT_RELATIONAL_OPERATOR node.png',
  NT_INT_TO_FLOAT: 'MATERIALX_CONVERT_node.png',
  NT_STRING: 'VALUE STRING node.png',

  // Kernels
  NT_KERN_DIRECTLIGHTING: 'RENDER KERNEL node.png',
  NT_KERN_INFO: 'RENDER KERNEL node.png',
  NT_KERN_MATPREVIEW: 'RENDER KERNEL node.png',
  NT_KERN_PATHTRACING: 'RENDER KERNEL node.png',
  NT_KERN_PHOTONTRACING: 'RENDER KERNEL node.png',
  NT_KERN_PMC: 'RENDER KERNEL node.png',

  // Lights
  NT_LIGHT_ANALYTIC: 'ANALYTIC_LIGHT node.png',
  NT_LIGHT_ANALYTIC_INTERNAL: 'ANALYTIC_LIGHT node.png',
  NT_LIGHT_DIRECTIONAL: 'DIRECTIONAL_LIGHT node.png',
  NT_LIGHT_QUAD: 'QUAD_LIGHT node.png',
  NT_LIGHT_SPHERE: 'SPHERE_LIGHT node.png',
  NT_LIGHT_VOLUME_SPOT: 'SPOT_LIGHT node.png',
  NT_TOON_DIRECTIONAL_LIGHT: 'TOON_DIRECTIONAL_LIGHT node.png',
  NT_TOON_POINT_LIGHT: 'TOON_POINT_LIGHT node.png',

  // Material Layers
  NT_MAT_COMPOSITE: 'COMPOSITE_MATERIAL node.png',
  NT_MAT_DIFFUSE_LAYER: 'MATERIAL_DIFFUSE_LAYER node.png',
  NT_MAT_LAYER: 'MATERIAL_LAYER node.png',
  NT_MAT_LAYER_GROUP: 'MATERIAL_LAYER_GROUP node.png',
  NT_MAT_METALLIC_LAYER: 'MATERIAL_METALLIC_LAYER node.png',
  NT_MAT_SHEEN_LAYER: 'MATERIAL_SHEEN_LAYER node.png',
  NT_MAT_SPECULAR_LAYER: 'MATERIAL_SPECULAR_LAYER node.png',

  // Materials
  NT_MAT_CLIPPING: 'CLIPPING_MATERIAL node.png',
  NT_MAT_DIFFUSE: 'DIFFUSE_MATERIAL node.png',
  NT_MAT_GLOSSY: 'GLOSSY_MATERIAL node.png',
  NT_MAT_HAIR: 'HAIR_MATERIAL node.png',
  NT_MAT_METAL: 'METAL_MATERIAL node.png',
  NT_MAT_MIX: 'MIX_MATERIAL node.png',
  NT_MAT_NULL: 'NULL_MATERIAL node.png',
  NT_MAT_PORTAL: 'PORTAL_MATERIAL node.png',
  NT_MAT_SHADOW_CATCHER: 'SHADOW_CATCHER_MATERIAL node.png',
  NT_MAT_SPECULAR: 'SPECULAR_MATERIAL node.png',
  NT_MAT_TOON: 'TOON_MATERIAL node.png',
  NT_MAT_UNIVERSAL: 'UNIVERSAL_MATERIAL node.png',

  // Medium
  NT_MED_ABSORPTION: 'ABSORPTION_MEDIUM node.png',
  NT_MED_SCATTERING: 'SCATTERING_MEDIUM node.png',

  // Imagers and Post Processing

  // Projection
  NT_PROJ_BOX: 'BOX_PROJECTION node.png',
  NT_PROJ_CYLINDRICAL: 'CYLINDRICAL_PROJECTION node.png',
  NT_PROJ_OSL: 'OSL_PROJECTION node.png',
  NT_PROJ_PERSPECTIVE: 'PERSPECTIVE_PROJECTION node.png',
  NT_PROJ_SPHERICAL: 'SPHERICAL_PROJECTION node.png',
  NT_PROJ_TRIPLANAR: 'TRIPLANAR_PROJECTION node.png',
  NT_PROJ_UVW: 'UVW_PROJECTION node.png',

  // Textures - Basic
  NT_TEX_CHECKS: 'CHECKS_TEXTURE node.png',
  NT_TEX_CLAMP: 'CLAMP_TEXTURE node.png',
  NT_TEX_CURVATURE: 'CURVATURE_TEXTURE node.png',
  NT_TEX_DIRT: 'DIRT_TEXTURE node.png',
  NT_TEX_FALLOFF: 'FALLOFF_TEXTURE node.png',
  NT_TEX_FLOAT: 'FLOAT_TEXTURE node.png',
  NT_TEX_GRADIENT: 'GRADIENT_TEXTURE node.png',
  NT_TEX_IMAGE: 'IMAGE_TEXTURE node.png',
  NT_TEX_INVERT: 'INVERT_TEXTURE node.png',
  NT_TEX_MARBLE: 'MARBLE_TEXTURE node.png',
  NT_TEX_MIX: 'MIX_TEXTURE node.png',
  NT_TEX_MULTIPLY: 'MULTIPLY_TEXTURE node.png',
  NT_TEX_NOISE: 'NOISE_TEXTURE node.png',
  NT_TEX_OSL: 'OSL_TEXTURE node.png',
  NT_TEX_RGB: 'TEXTURE_SPECTRUM node.png',
  NT_TEX_SIDE: 'SIDE_TEXTURE node.png',
  NT_TEX_TRIPLANAR: 'TRIPLANAR_IMAGE node.png',
  NT_TEX_TURBULENCE: 'TURBULENCE_TEXTURE node.png',

  // Transforms
  NT_TRANSFORM_2D: '2D_TRANSFORMATION node.png',
  NT_TRANSFORM_3D: '3D_TRANSFORMATION node.png',
  NT_TRANSFORM_ROTATION: '3D_ROTATION node.png',
  NT_TRANSFORM_SCALE: '3D_SCALE node.png',
  NT_TRANSFORM_VALUE: 'TRANSFORM_VALUE node.png',

  // Output and Render
  NT_RENDER_AOV_GROUP: 'aov-output-group.png',
  NT_RENDER_LAYER: 'render_layer.png',
  NT_RENDER_PASSES: 'render_layer.png',

  // Output AOVs
  NT_OUT_EMISSION: 'aov-output-group.png',
  NT_OUT_OCIO_COLOR_SPACE: 'OCIO_COLOR_SPACE node.png',
  NT_OUT_OCIO_LOOK: 'OCIO_LOOK node.png',
  NT_OUT_OCIO_VIEW: 'OCIO_VIEW node.png',

  // Film and Settings
  NT_FILM_SETTINGS: 'FILM node.png',

  // Animation and Settings
  NT_ANIMATION_SETTINGS: 'animation_settings_node.png',

  // Blending Settings
  NT_BLENDING_SETTINGS: 'BLENDING_SETTINGS node.png',

  // OSL and MaterialX nodes

  // Round Edges
  NT_ROUND_EDGES: 'ROUND_EDGES node.png',

  // Trace Sets
  NT_TRACE_SET_VISIBILITY_RULE: 'TRACE_SET_VISIBILITY_RULE node.png',
  NT_TRACE_SET_VISIBILITY_RULE_GROUP: 'TRACE_SET_VISIBILITY_RULE_GROUP node.png',

  // Object Layers

  // Phase Functions
  NT_PHASE_SCHLICK: 'SCHLICK node.png',

  // Render Target
  NT_RENDERTARGET: 'RENDER_TARGET node.png',

  // In/Out/Switch nodes - generic icons
  NT_IN_ANIMATION_SETTINGS: 'animation_settings_node.png',
  NT_IN_BIT_MASK: 'BITMASK_IN node.png',
  NT_IN_BLENDING_SETTINGS: 'BLENDING_SETTINGS_IN node.png',
  NT_IN_BOOL: 'BOOL_IN node.png',
  NT_IN_CAMERA: 'CAMERA_IN node.png',
  NT_IN_DISPLACEMENT: 'DISPLACEMENT_IN node.png',
  NT_IN_EMISSION: 'EMISSION_IN node.png',
  NT_IN_ENUM: 'ENUM_IN node.png',
  NT_IN_ENVIRONMENT: 'ENVIRONMENT_IN node.png',
  NT_IN_FILM_SETTINGS: 'FILM_SETTINGS_IN node.png',
  NT_IN_FLOAT: 'FLOAT_IN node.png',
  NT_IN_GEOMETRY: 'GEOMETRY_IN node.png',
  NT_IN_IMAGER: 'IMAGER_IN node.png',
  NT_IN_INT: 'INT_IN node.png',
  NT_IN_KERNEL: 'KERNEL_IN node.png',
  NT_IN_LUT: 'LUT_IN node.png',
  NT_IN_MATERIAL: 'MATERIAL_IN node.png',
  NT_IN_MATERIAL_LAYER: 'MATERIAL_LAYER_IN node.png',
  NT_IN_MEDIUM: 'MEDIUM_IN node.png',
  NT_IN_OBJECTLAYER: 'OBJECTLAYER_IN node.png',
  NT_IN_OCIO_COLOR_SPACE: 'OCIO_COLOR_SPACE_IN node.png',
  NT_IN_OCIO_LOOK: 'OCIO_LOOK_IN node.png',
  NT_IN_OCIO_VIEW: 'OCIO_VIEW_IN node.png',
  NT_IN_OFFSET: 'OFFSET_IN node.png',
  NT_IN_OUTPUT_AOV: 'OUTPUT_AOV_IN node.png',
  NT_IN_OUTPUT_AOV_GROUP: 'OUTPUT_AOV_GROUP_IN node.png',
  NT_IN_OUTPUT_AOV_LAYER: 'OUTPUT_AOV_LAYER_IN node.png',
  NT_IN_PHASEFUNCTION: 'PHASEFUNCTION_IN node.png',
  NT_IN_POSTPROCESSING: 'POSTPROC node.png',
  NT_IN_POST_VOLUME: 'POST_VOLUME_IN node.png',
  NT_IN_PROJECTION: 'PROJECTION_IN node.png',
  NT_IN_RENDERTARGET: 'RENDERTARGET_IN node.png',
  NT_IN_RENDER_JOB: 'RENDER_JOB_IN node.png',
  NT_IN_RENDER_LAYER: 'render_layer.png',
  NT_IN_RENDER_PASSES: 'RENDER_PASSES_IN node.png',
  NT_IN_ROUND_EDGES: 'ROUND_EDGES_IN node.png',
  NT_IN_STRING: 'STRING_IN node.png',
  NT_IN_TEXTURE: 'TEXTURE_IN node.png',
  NT_IN_TEX_COMPOSITE_LAYER: 'TEX_COMPOSITE_LAYER_IN node.png',
  NT_IN_TOON_RAMP: 'TOON_RAMP_IN node.png',
  NT_IN_TRACE_SET_VISIBILITY_RULE: 'TRACE_SET_VISIBILITY_RULE_IN node.png',
  NT_IN_TRACE_SET_VISIBILITY_RULE_GROUP: 'TRACE_SET_VISIBILITY_RULE_GROUP_IN node.png',
  NT_IN_TRANSFORM: 'TRANSFORM_IN node.png',
  NT_IN_VOLUME_RAMP: 'VOLUME_RAMP_IN node.png',

  // Switch nodes use switch icons
  NT_SWITCH_ANIMATION_SETTINGS: 'animation_settings_node.png',
  NT_SWITCH_BIT_MASK: 'BITMASK_SWITCH node.png',
  NT_SWITCH_BLENDING_SETTINGS: 'BLENDING_SETTINGS_SWITCH node.png',
  NT_SWITCH_BOOL: 'BOOL_SWITCH node.png',
  NT_SWITCH_CAMERA: 'CAMERA_SWITCH node.png',
  NT_SWITCH_DISPLACEMENT: 'DISPLACEMENT_SWITCH node.png',
  NT_SWITCH_EMISSION: 'EMISSION_SWITCH node.png',
  NT_SWITCH_ENUM: 'ENUM_SWITCH node.png',
  NT_SWITCH_ENVIRONMENT: 'ENVIRONMENT_SWITCH node.png',
  NT_SWITCH_FILM_SETTINGS: 'FILM_SETTINGS_SWITCH node.png',
  NT_SWITCH_FLOAT: 'FLOAT_SWITCH node.png',
  NT_SWITCH_GEOMETRY: 'GEOMETRY_SWITCH node.png',
  NT_SWITCH_IMAGER: 'IMAGER_SWITCH node.png',
  NT_SWITCH_INT: 'INT_SWITCH node.png',
  NT_SWITCH_INTERNAL: 'SWITCH node.png',
  NT_SWITCH_KERNEL: 'KERNEL_SWITCH node.png',
  NT_SWITCH_LUT: 'LUT_SWITCH node.png',
  NT_SWITCH_MATERIAL: 'MATERIAL_SWITCH node.png',
  NT_SWITCH_MATERIAL_LAYER: 'MATERIAL_LAYER_SWITCH node.png',
  NT_SWITCH_MEDIUM: 'MEDIUM_SWITCH node.png',
  NT_SWITCH_OBJECTLAYER: 'OBJECTLAYER_SWITCH node.png',
  NT_SWITCH_OCIO_COLOR_SPACE: 'OCIO_COLOR_SPACE_SWITCH node.png',
  NT_SWITCH_OCIO_LOOK: 'OCIO_LOOK_SWITCH node.png',
  NT_SWITCH_OCIO_VIEW: 'OCIO_VIEW_SWITCH node.png',
  NT_SWITCH_OFFSET: 'OFFSET_SWITCH node.png',
  NT_SWITCH_OUTPUT_AOV: 'OUTPUT_AOV_SWITCH node.png',
  NT_SWITCH_OUTPUT_AOV_GROUP: 'OUTPUT_AOV_GROUP_SWITCH node.png',
  NT_SWITCH_OUTPUT_AOV_LAYER: 'OUTPUT_AOV_LAYER_SWITCH node.png',
  NT_SWITCH_PHASEFUNCTION: 'PHASEFUNCTION_SWITCH node.png',
  NT_SWITCH_POSTPROCESSING: 'POSTPROC node.png',
  NT_SWITCH_POST_VOLUME: 'POST_VOLUME_SWITCH node.png',
  NT_SWITCH_PROJECTION: 'PROJECTION_SWITCH node.png',
  NT_SWITCH_RENDERTARGET: 'RENDERTARGET_SWITCH node.png',
  NT_SWITCH_RENDER_JOB: 'RENDER_JOB_SWITCH node.png',
  NT_SWITCH_RENDER_LAYER: 'render_layer.png',
  NT_SWITCH_RENDER_PASSES: 'RENDER_PASSES_SWITCH node.png',
  NT_SWITCH_ROUND_EDGES: 'ROUND_EDGES_SWITCH node.png',
  NT_SWITCH_STRING: 'STRING_SWITCH node.png',
  NT_SWITCH_TEXTURE: 'TEXTURE_SWITCH node.png',
  NT_SWITCH_TEX_COMPOSITE_LAYER: 'TEX_COMPOSITE_LAYER_SWITCH node.png',
  NT_SWITCH_TOON_RAMP: 'TOON_RAMP_SWITCH node.png',
  NT_SWITCH_TRACE_SET_VISIBILITY_RULE: 'TRACE_SET_VISIBILITY_RULE_SWITCH node.png',
  NT_SWITCH_TRACE_SET_VISIBILITY_RULE_GROUP: 'TRACE_SET_VISIBILITY_RULE_GROUP_SWITCH node.png',
  NT_SWITCH_TRANSFORM: 'TRANSFORM_SWITCH node.png',
  NT_SWITCH_VOLUME_RAMP: 'VOLUME_RAMP_SWITCH node.png',

  // Annotation and Categories
  NT_ANNOTATION: 'ANNOTATION node.png',
};

/**
 * Get icon path for a node type
 * @param nodeType NT_ enum string
 * @returns path to icon file
 */
export function getNodeIconPath(nodeType: string): string {
  if (hasIconMapping(nodeType)) {
    const iconFile = nodeIconMapping[nodeType];
    if (iconFile) {
      return `/icons/${iconFile}`;
    }
  }
  return '/icons/EMPTY.png';
}

/**
 * Check if a node type has an icon mapping
 */
export function hasIconMapping(nodeType: string): boolean {
  return nodeType in nodeIconMapping;
}
