/**
 * Static Octane API metadata cache.
 *
 * Loads `mcp/data/octane-api-cache.json` (generated by scripts/fetch-api-cache.js)
 * and provides instant lookups for node types, pin layouts, and type compatibility.
 *
 * Eliminates hundreds of gRPC round-trips per scene build.
 */

import fs from 'fs';
import path from 'path';

const CACHE_PATH = path.resolve(__dirname, '../data/octane-api-cache.json');

export interface CachedPinInfo {
  index: number;
  id: string; // e.g. "P_DIFFUSE"
  type: string; // e.g. "PT_TEXTURE"
  staticName: string; // e.g. "diffuse"
  staticLabel: string; // e.g. "Diffuse"
  defaultNodeType?: string; // e.g. "NT_TEX_RGB" — if set, Octane auto-creates a child here
  description?: string;
  pinColor?: number;
}

export interface CachedNodeTypeInfo {
  name: string;
  description: string;
  outType: string; // e.g. "PT_MATERIAL"
  category: string;
  defaultName: string;
  nodeColor: number;
  isHidden: boolean;
  isCreatableByApi: boolean;
  pinInfoCount: number;
  attributeInfoCount: number;
  movableInputPinCount: number;
  movableInputName: string;
  pins: CachedPinInfo[];
}

interface CacheData {
  meta: {
    octaneVersion: number;
    octaneName: string;
    generatedAt: string;
    nodeTypeCount: number;
    pinTypeCount: number;
    totalPins: number;
  };
  pinTypes: Record<string, { color: number }>;
  attributeTypes: Record<string, string>;
  nodeTypes: Record<string, CachedNodeTypeInfo>;
  nodeTypesByName: Record<string, string>;
  compatibleTypes: Record<string, { nodes: string[]; graphs: string[] }>;
}

export class ApiCache {
  private data: CacheData;
  private typeIdToName: Map<number, string>; // reverse lookup: numeric type ID → "NT_..."

  /** Load cache from default path. Returns null if file missing. */
  static load(): ApiCache | null {
    if (!fs.existsSync(CACHE_PATH)) return null;
    try {
      return new ApiCache(CACHE_PATH);
    } catch (e) {
      console.error('Failed to load API cache:', e);
      return null;
    }
  }

  constructor(cachePath: string) {
    const raw = fs.readFileSync(cachePath, 'utf-8');
    this.data = JSON.parse(raw);

    // Build reverse map: numeric type ID → type name
    this.typeIdToName = new Map();
    for (const [name, id] of Object.entries(this.data.nodeTypesByName)) {
      this.typeIdToName.set(Number(id), name);
    }
  }

  /** Get full info for a node type by enum name (e.g. "NT_MAT_UNIVERSAL") */
  getNodeType(typeName: string): CachedNodeTypeInfo | undefined {
    return this.data.nodeTypes[typeName];
  }

  /** Get node type name from numeric type ID (e.g. 130 → "NT_MAT_UNIVERSAL") */
  getNodeTypeName(typeId: number): string | undefined {
    return this.typeIdToName.get(typeId);
  }

  /** Get full info for a node type by numeric ID */
  getNodeTypeById(typeId: number): CachedNodeTypeInfo | undefined {
    const name = this.typeIdToName.get(typeId);
    return name ? this.data.nodeTypes[name] : undefined;
  }

  /** Get the output pin type name for a node type (e.g. "PT_MATERIAL") */
  getOutType(typeName: string): string | undefined {
    return this.data.nodeTypes[typeName]?.outType;
  }

  /** Get all pins for a node type */
  getPins(typeName: string): CachedPinInfo[] | undefined {
    return this.data.nodeTypes[typeName]?.pins;
  }

  /** Get a specific pin by index */
  getPinByIndex(typeName: string, index: number): CachedPinInfo | undefined {
    return this.data.nodeTypes[typeName]?.pins?.find(p => p.index === index);
  }

  /** Get a specific pin by name */
  getPinByName(typeName: string, name: string): CachedPinInfo | undefined {
    return this.data.nodeTypes[typeName]?.pins?.find(p => p.staticName === name);
  }

  /** Check if a source node type can connect to a target node type's pin */
  isCompatible(sourceTypeName: string, targetTypeName: string, pinIndex: number): boolean {
    const sourceInfo = this.data.nodeTypes[sourceTypeName];
    const targetInfo = this.data.nodeTypes[targetTypeName];
    if (!sourceInfo || !targetInfo) return true; // unknown = allow (let Octane decide)

    const pin = targetInfo.pins?.find(p => p.index === pinIndex);
    if (!pin) return true;

    return (
      sourceInfo.outType === pin.type ||
      pin.type === 'PT_UNKNOWN' ||
      sourceInfo.outType === 'PT_UNKNOWN'
    );
  }

  /** Get nodes compatible with a pin type */
  getCompatibleNodes(pinType: string): string[] {
    return this.data.compatibleTypes[pinType]?.nodes ?? [];
  }

  /** Get all available node type names */
  getNodeTypeNames(): string[] {
    return Object.keys(this.data.nodeTypes);
  }

  get version(): string {
    return this.data.meta.octaneName;
  }

  get nodeTypeCount(): number {
    return this.data.meta.nodeTypeCount;
  }

  get totalPins(): number {
    return this.data.meta.totalPins;
  }
}
